using UnityEngine;
namespace BrineGame {
 public sealed class ComicImpactVisuals:MonoBehaviour {
  readonly Mesh[] meshes=new Mesh[12];readonly MeshRenderer[] fills=new MeshRenderer[12];readonly LineRenderer[] edges=new LineRenderer[12];Material ink;Transform root;
  public void Build(){root=new GameObject("Wordless comic punch impact").transform;root.SetParent(transform,false);ink=new Material(Shader.Find("Sprites/Default"));for(int i=0;i<12;i++){var go=new GameObject("Impact shape "+i);go.transform.SetParent(root,false);meshes[i]=new Mesh();go.AddComponent<MeshFilter>().sharedMesh=meshes[i];fills[i]=go.AddComponent<MeshRenderer>();fills[i].sharedMaterial=ink;fills[i].sortingOrder=30+i*2;edges[i]=go.AddComponent<LineRenderer>();edges[i].sharedMaterial=ink;edges[i].useWorldSpace=false;edges[i].loop=true;edges[i].sortingOrder=31+i*2;}}
  void Shape(int id,Vector2[] points,Color color,float alpha,float width){int n=points.Length;var verts=new Vector3[n+1];var colors=new Color[n+1];var tris=new int[n*3];var outline=new Vector3[n];color.a=alpha;for(int i=0;i<n;i++){verts[i]=outline[i]=new Vector3(points[i].x/100,-points[i].y/100,0);colors[i]=color;tris[i*3]=n;tris[i*3+1]=i;tris[i*3+2]=(i+1)%n;}for(int i=0;i<n;i++)verts[n]+=verts[i]/n;colors[n]=color;meshes[id].Clear();meshes[id].vertices=verts;meshes[id].colors=colors;meshes[id].triangles=tris;meshes[id].RecalculateBounds();edges[id].positionCount=n;edges[id].SetPositions(outline);edges[id].startWidth=edges[id].endWidth=width/100;edges[id].startColor=edges[id].endColor=new Color(24/255f,38/255f,39/255f,alpha);}
  void Star(int id,float radius,int n,float turn,Color color,float alpha){var p=new Vector2[n*2];for(int i=0;i<p.Length;i++){float a=turn+i*Mathf.PI/n,r=radius*(i%2==1?.42f:1)*(1+.1f*Mathf.Sin(i*4.7f));p[i]=new Vector2(Mathf.Cos(a)*r,Mathf.Sin(a)*r*.82f);}Shape(id,p,color,alpha,2.5f);}
  public void Render(EncounterModel m){ShotEffect hit=null;foreach(var e in m.Effects)if(e.impact&&e.weapon=="melee"&&e.duration-e.life<.22f+.08f*e.power)hit=e;root.gameObject.SetActive(hit!=null);if(hit==null)return;root.position=BrineGameController.World(hit.x,hit.y);float power=hit.power,t=(hit.duration-hit.life)/(.22f+.08f*power),size=(24+28*Mathf.Sin(Mathf.Min(1,t*3)*Mathf.PI/2))*power,fade=Mathf.Pow(1-t,.65f);Color rust=new Color32(191,75,43,255),gold=new Color32(240,182,79,255),cream=new Color32(255,242,205,255);Star(0,size*1.12f,11,.06f,new Color32(18,29,33,255),fade);Star(1,size,9,.13f,rust,fade);Star(2,size*.77f,7,-.24f,gold,fade);Star(3,size*(t<.16f?.63f:.38f),6,.2f,cream,fade);for(int i=0;i<8;i++){float a=i*Mathf.PI/4+.14f,d=(25+62*t)*power,r=(1-t)*7*power,rotation=a+t;var center=new Vector2(Mathf.Cos(a)*d,Mathf.Sin(a)*d*.8f);var p=new[]{new Vector2(-r,-r*.5f),new Vector2(r*2.7f,0),new Vector2(-r,r*.5f)};for(int j=0;j<3;j++)p[j]=center+new Vector2(p[j].x*Mathf.Cos(rotation)-p[j].y*Mathf.Sin(rotation),p[j].x*Mathf.Sin(rotation)+p[j].y*Mathf.Cos(rotation));Shape(4+i,p,i%2==1?gold:cream,fade,2f);}}
  void OnDestroy(){foreach(var mesh in meshes)if(mesh)Destroy(mesh);if(ink)Destroy(ink);}
 }
}
