using System;
namespace BrineGame {
 [Serializable] public class HarborProgressData {
 public int version=1;public int[] materials=new int[3],build=new int[3],weaponXP=new int[3],formXP=new int[2],guide=new int[6],counts=new int[5];public bool[] district=new bool[3];public string[] weaponPath=new string[3],formPath=new string[2];public string contract="road",notice="Reclaim the harbor. Defeat Foreman Rusk.";public int completed,expedition=-1;public long finish,clock;
 }
 public static class HarborProgress {
 public static readonly string[] Weapons={"scrap","repeater","lowtide"},Forms={"step-shell","samurai"},Buildings={"Workshop","Ferry Dock","Lighthouse"},Captains={"Foreman Rusk","Valve-Mother Venn","Marshal Flint"},Contracts={"Clear the boards","Make some room","Clean cuts","Gatecrashers","Break the blockade"},ContractIds={"road","shell","samurai","guard","captain"},Expeditions={"Shore sweep","Channel survey","Wreck recovery"};
 public static readonly int[] Targets={12,8,8,4,2},Seconds={180,900,2700};
 public static readonly int[][] Costs={new[]{12,3,0},new[]{18,4,0},new[]{24,6,1}},ContractRewards={new[]{8,2,0},new[]{12,3,0},new[]{12,3,0},new[]{10,4,1},new[]{10,5,1}},CaptainRewards={new[]{12,6,1},new[]{20,9,2},new[]{30,12,3}},Cargo={new[]{10,2,0},new[]{16,4,2},new[]{30,12,3}};
 public static readonly string[][] Paths={new[]{"pierce","impact"},new[]{"pierce","tempo"},new[]{"shatter","impact"}},FormPaths={new[]{"bastion","mend"},new[]{"execute","flow"}};
 public static readonly string[] BuildingUnlocks={"Weapon mastery paths / then +5%, +10% gun damage","Crew expeditions / longer routes each level","Form paths / then +5%, +10% salvage"};
 static int Clamp(int v,int max=1000000)=>Math.Max(0,Math.Min(max,v));
 static int[] Sanitize(int[] a,int length,int max=1000000){var r=new int[length];for(int i=0;i<length;i++)r[i]=Clamp(a!=null&&a.Length>i?a[i]:0,max);return r;}
 public static HarborProgressData Load(HarborProgressData p){if(p==null||p.version!=1)return new HarborProgressData();p.materials=Sanitize(p.materials,3);p.build=Sanitize(p.build,3,3);p.weaponXP=Sanitize(p.weaponXP,3);p.formXP=Sanitize(p.formXP,2);p.guide=Sanitize(p.guide,6);p.counts=Sanitize(p.counts,5,100);if(p.district==null||p.district.Length!=3)p.district=new bool[3];if(p.weaponPath==null||p.weaponPath.Length!=3)p.weaponPath=new string[3];if(p.formPath==null||p.formPath.Length!=2)p.formPath=new string[2];for(int i=0;i<3;i++)if(Array.IndexOf(Paths[i],p.weaponPath[i])<0)p.weaponPath[i]="";for(int i=0;i<2;i++)if(Array.IndexOf(FormPaths[i],p.formPath[i])<0)p.formPath[i]="";if(Array.IndexOf(ContractIds,p.contract)<0)p.contract="road";if(p.expedition<0||p.expedition>2||p.finish<=0)p.expedition=-1;p.clock=Math.Max(0,p.clock);return p;}
 public static string Materials(int[] a)=>a[0]+" timber / "+a[1]+" brass / "+a[2]+" charts";
 public static void Award(HarborProgressData p,int[] a){for(int i=0;i<3;i++)p.materials[i]=Clamp(p.materials[i]+a[i]);}
 public static int[] Cost(HarborProgressData p,int b){return new[]{Costs[b][0]*(p.build[b]+1),Costs[b][1]*(p.build[b]+1),Costs[b][2]*(p.build[b]+1)};}
 public static bool CanBuild(HarborProgressData p,int b){if(b<0||b>2||p.build[b]>=3||!p.district[0])return false;var cost=Cost(p,b);for(int i=0;i<3;i++)if(p.materials[i]<cost[i])return false;return true;}
 public static bool Build(HarborProgressData p,int b){if(!CanBuild(p,b))return false;var cost=Cost(p,b);for(int i=0;i<3;i++)p.materials[i]-=cost[i];p.build[b]++;p.notice=Buildings[b]+" restored to level "+p.build[b];return true;}
 public static int Tier(int xp)=>xp>=140?3:xp>=60?2:xp>=20?1:0;
 public static bool ChooseWeapon(HarborProgressData p,int i,string path){if(i<0||i>2||p.build[0]==0||Tier(p.weaponXP[i])==0||Array.IndexOf(Paths[i],path)<0)return false;p.weaponPath[i]=path;return true;}
 public static bool ChooseForm(HarborProgressData p,int i,string path){if(i<0||i>1||p.build[2]==0||p.formXP[i]<12||Array.IndexOf(FormPaths[i],path)<0)return false;p.formPath[i]=path;return true;}
 public static bool Claim(HarborProgressData p){int i=Array.IndexOf(ContractIds,p.contract);if(p.counts[i]<Targets[i])return false;p.counts[i]-=Targets[i];Award(p,ContractRewards[i]);p.completed++;p.notice=Contracts[i]+" complete. Materials delivered.";return true;}
 public static bool Dispatch(HarborProgressData p,int id,long time){if(id<0||id>2||p.expedition>=0||p.build[1]<id+1)return false;p.clock=Math.Max(p.clock,time);p.expedition=id;p.finish=p.clock+Seconds[id]*1000;return true;}
 public static bool Collect(HarborProgressData p,long time){p.clock=Math.Max(time,p.clock);if(p.expedition<0||p.clock<p.finish)return false;Award(p,Cargo[p.expedition]);p.notice=Expeditions[p.expedition]+" cargo collected.";p.expedition=-1;p.finish=0;return true;}
 public static int Hit(EncounterModel m,int damage,string weapon){var p=m.Progress;int w=Array.IndexOf(Weapons,weapon),f=Array.IndexOf(Forms,m.SelectedForm),g=Array.FindIndex(EncounterModel.Enemies,e=>e.Art==m.Enemy.Art);double d=damage;if(g>=0&&p.guide[g]>=15)d*=1.1;if(weapon=="melee"){p.formXP[f]=Clamp(p.formXP[f]+1);if(p.formPath[f]=="execute"&&m.Health/(float)m.MaxHealth<.35)d*=1.5;if(p.formPath[f]=="mend")m.PlayerHealth=Math.Min(m.MaxPlayerHealth,m.PlayerHealth+Math.Max(1,(int)Math.Round(m.MaxPlayerHealth*.02)));if(p.formPath[f]=="flow")m.UltimateCharge=Math.Min(100,m.UltimateCharge+3);}else if(w>=0){int t=Tier(p.weaponXP[w]);if(p.weaponPath[w]=="impact")d*=1+t*.25;if(p.weaponPath[w]=="pierce"&&m.Guarded)d/=.35;if(p.weaponPath[w]=="shatter")m.Shattered=Math.Min(.24f,t*.08f);p.weaponXP[w]=Clamp(p.weaponXP[w]+1);}return (int)Math.Floor(d+.5);}
 public static void Kill(EncounterModel m,string weapon){var p=m.Progress;int g=Array.FindIndex(EncounterModel.Enemies,e=>e.Art==m.Enemy.Art);if(g>=0)p.guide[g]=Clamp(p.guide[g]+1);Award(p,new[]{1,m.Boss?3:0,0});int i=Array.IndexOf(ContractIds,p.contract);if(i==0||i==1&&weapon=="melee"&&m.SelectedForm=="step-shell"||i==2&&weapon=="melee"&&m.SelectedForm=="samurai"||i==3&&m.Enemy.Art=="gate-hauler"||i==4&&m.Boss)p.counts[i]=Math.Min(Targets[i],p.counts[i]+1);if(p.counts[i]>=Targets[i])p.notice="Contract complete: "+Contracts[i];int d=m.Route;if(m.Boss&&m.Stage>=(d+1)*5&&!p.district[d]){p.district[d]=true;Award(p,CaptainRewards[d]);if(d==1){if(m.Weapon=="scrap")m.Mods.damage=Math.Min(3,m.Mods.damage+1);else if(m.Weapon=="repeater")m.Mods.shell=Math.Min(3,m.Mods.shell+1);else m.Mods.speed=Math.Min(3,m.Mods.speed+1);}if(d==2)for(int j=0;j<3;j++)p.weaponXP[j]=Clamp(p.weaponXP[j]+100);p.notice=Captains[d]+" defeated. District reclaimed!";}}
 public static string Next(HarborProgressData p){if(!p.district[0])return "Defeat Foreman Rusk / Dry Docks 5+ / workshop permit";for(int i=0;i<3;i++)if(p.build[i]==0)return "Restore "+Buildings[i]+" / "+BuildingUnlocks[i].Split('/')[0];for(int i=1;i<3;i++)if(!p.district[i])return "Defeat "+Captains[i]+" / "+EncounterModel.Routes[i]+" "+((i+1)*5)+"+";for(int i=0;i<3;i++)if(p.build[i]<3)return "Improve "+Buildings[i]+" to level "+(p.build[i]+1);return "Harbor restored / master weapons and field guide";}
 }
}
