using System;
using UnityEngine;
namespace BrineGame {
 public sealed partial class HarborUI {
 readonly Texture2D[] restorationArt=new Texture2D[3];
 int progressionPage;Vector2 progressScroll;bool harborSettings;
 readonly string[] progressLabels={"HARBOR","CONTRACTS","WEAPONS","FORMS","GUIDE","EXPEDITIONS","DISTRICTS"};
 void DrawGrowth(){var m=game.Model;var p=m.Progress;if(p.district[m.Route]){Fill(415,140,2,60,Dark);Fill(417,140,23,17,"#f19a76");}if(m.Boss){Frame(153,142,144,32,Orange);Text("CAPTAIN",159,146,132,9,8,Cream,TextAnchor.MiddleCenter);Text(HarborProgress.Captains[m.Route].ToUpper(),159,156,132,14,12,Cream,TextAnchor.MiddleCenter);}if(objectiveSign==null)objectiveSign=Resources.Load<Texture2D>("ui/harbor-objective");if(objectiveSign!=null)GUI.DrawTextureWithTexCoords(new Rect(9,329,432,34),objectiveSign,new Rect(40f/2048,1-473f/683,1968f/2048,272f/683));else Fill(9,329,432,34,Teal);int ci=Array.IndexOf(HarborProgress.ContractIds,p.contract);bool ready=comicReady.Count>0;Text(ready?comicReady.Count+" REWARD(S) READY":"NEXT GOAL",78,334,295,8,7,ready?Cream:"#f19a76");var gs=new GUIStyle{font=bodyFont,fontSize=10,wordWrap=true};gs.normal.textColor=C(Cream);GUI.Label(new Rect(78,342,295,20),ready?"Rewards waiting / tap to collect":HarborProgress.Next(p),gs);if(Hot(9,329,432,34,"Open harbor goals")){tab="camp";progressionPage=ready?comicReadyPage:0;}}

 void PLine(string text,float y,int size=12){var st=new GUIStyle{font=bodyFont,fontSize=size,wordWrap=true};st.normal.textColor=C(Dark);GUI.Label(new Rect(5,y,367,38),text,st);}
 void PMeter(int value,int max,float y){Fill(5,y,367,12,Teal);Fill(5,y,367*Mathf.Clamp01(value/(float)max),12,Orange);Text(Math.Min(value,max)+" / "+max,10,y,350,12,9,Cream);}
 bool PButton(string label,float y,bool enabled=true){GUI.enabled=enabled;bool result=Button(label,5,y,367,27);GUI.enabled=true;return result;}
 void ProgressionDrawer(){var m=game.Model;var p=m.Progress;Ticket(9,434,432,280);Text("HARBOR",22,444,300,28,25);if(Button("X",401,443,28,28))tab="road";
 for(int i=0;i<7;i++){int id=i;if(Button(progressLabels[i],20+(i%4)*101,478+(i/4)*24,98,22,progressionPage==i)){progressionPage=id;progressScroll=Vector2.zero;}}
 progressScroll=GUI.BeginScrollView(new Rect(20,531,410,169),progressScroll,new Rect(0,0,387,progressionPage==0?1250:progressionPage==1?900:progressionPage==2?700:progressionPage==3?525:progressionPage==4?800:progressionPage==5?560:650));PLine(HarborProgress.Materials(p.materials),0);PLine(p.notice,28);float y=70;
 if(progressionPage==0){PLine(HarborProgress.Next(p),y);y+=45;for(int i=0;i<3;i++){int id=i;Text(HarborProgress.Buildings[i]+" / "+p.build[i]+" OF 3",5,y,367,24,20);y+=25;if(restorationArt[i]==null)restorationArt[i]=Resources.Load<Texture2D>("restoration/"+HarborGrowth.ArtNames[i]);
 if(p.build[i]>0&&restorationArt[i]!=null){var tex=restorationArt[i];float h=145,w=h*512/HarborGrowth.FrameHeight[i];GUI.DrawTextureWithTexCoords(new Rect(5+(367-w)/2,y,w,h),tex,new Rect((p.build[i]-1)/3f,(1024-HarborGrowth.FrameY[i]-HarborGrowth.FrameHeight[i])/1024f,1/3f,HarborGrowth.FrameHeight[i]/1024f),true);y+=153;}
 PLine(HarborProgress.BuildingUnlocks[i],y);y+=35;PMeter(p.build[i],3,y);y+=18;PLine(!p.district[0]?"Defeat Foreman Rusk for the workshop permit":p.build[i]==3?"Fully restored":HarborProgress.Materials(HarborProgress.Cost(p,i)),y);y+=36;if(PButton("RESTORE / IMPROVE",y,HarborProgress.CanBuild(p,i)))Act(()=>HarborProgress.Build(p,id));y+=40;}if(PButton(m.Paused?"RESUME BATTLE":"PAUSE BATTLE",y))m.Paused=!m.Paused;y+=35;if(PButton("SETTINGS / FRESH SAVE",y))harborSettings=!harborSettings;y+=35;if(harborSettings){if(!confirm){if(PButton("FRESH SAVE...",y))confirm=true;}else{if(PButton("ERASE SAVE",y)){Act(()=>m.Reset());confirm=false;}y+=32;if(PButton("KEEP SAVE",y))confirm=false;}}}
 if(progressionPage==1){string[] desc={"Defeat 12 enemies with any weapon or form.","Finish 8 enemies with Step Shell melee.","Finish 8 enemies with Samurai melee.","Defeat 4 Gate Haulers.","Defeat 2 captains on any route."};for(int i=0;i<5;i++){int id=i;Text(HarborProgress.Contracts[i],5,y,367,22,19);y+=25;PLine(desc[i],y);y+=30;PMeter(p.counts[i],HarborProgress.Targets[i],y);y+=18;PLine("Reward: "+HarborProgress.Materials(HarborProgress.ContractRewards[i]),y);y+=32;bool selected=p.contract==HarborProgress.ContractIds[i];if(PButton(selected?"COLLECT REWARD":"TRACK CONTRACT",y,!selected||p.counts[i]>=HarborProgress.Targets[i]))Act(()=>{if(selected)HarborProgress.Claim(p);else p.contract=HarborProgress.ContractIds[id];});y+=45;}}
 if(progressionPage==2){string[][] desc={new[]{"PIERCE / bypass guard","IMPACT / +25% damage per tier"},new[]{"PIERCE / bypass guard","TEMPO / 15% faster per tier"},new[]{"SHATTER / weaken attacks 8% per tier","IMPACT / +25% damage per tier"}};PLine("Workshop required. Tiers at 20, 60 and 140 successful gun hits.",y);y+=45;for(int i=0;i<3;i++){int id=i,t=HarborProgress.Tier(p.weaponXP[i]);Text(m.Settings.weapons[i].name+" / TIER "+t+" OF 3",5,y,367,23,20);y+=26;PMeter(p.weaponXP[i],t==0?20:t==1?60:140,y);y+=25;for(int j=0;j<2;j++){string path=HarborProgress.Paths[i][j];if(PButton((p.weaponPath[i]==path?"EQUIPPED / ":"")+desc[i][j],y,p.build[0]>0&&t>0&&!m.UltimateActive))Act(()=>HarborProgress.ChooseWeapon(p,id,path));y+=36;}y+=20;}}
 if(progressionPage==3){string[][] desc={new[]{"BASTION / 85% damage resistance","LIVING ARMOR / heal 2% per hit"},new[]{"FINISHER / +50% vs low-health enemies","FLOW / bank 3 charge per melee hit"}};PLine("Lighthouse required. Land 12 melee contacts to specialize.",y);y+=45;for(int i=0;i<2;i++){int id=i;Text(i==0?"STEP SHELL":"SAMURAI",5,y,367,23,20);y+=26;PMeter(p.formXP[i],12,y);y+=25;for(int j=0;j<2;j++){string path=HarborProgress.FormPaths[i][j];if(PButton((p.formPath[i]==path?"EQUIPPED / ":"")+desc[i][j],y,p.build[2]>0&&p.formXP[i]>=12&&!m.UltimateActive))Act(()=>HarborProgress.ChooseForm(p,id,path));y+=36;}y+=20;}}
 if(progressionPage==4){string[] tips={"Lobs heavy projectiles. Upgrade shell.","Fires three quick shots.","Slow heavy slam. Build shell before pushing.","Guards against gunfire. Melee / pierce bypass it.","Repairs 12% health on attacks. Use burst damage.","Burrows. Melee connects while gunfire misses."};for(int i=0;i<6;i++){Text(EncounterModel.Enemies[i].Name,5,y,367,24,19);y+=28;PMeter(p.guide[i],15,y);y+=20;PLine(p.guide[i]>=3?tips[i]:"Tactics reveal after 3 defeats.",y);y+=35;PLine(p.guide[i]>=15?"STUDIED / permanent +10% damage":"15 defeats unlock +10% damage.",y);y+=38;}}
 if(progressionPage==5){long now=DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();if(p.expedition>=0){long left=Math.Max(0,(p.finish-Math.Max(now,p.clock)+999)/1000);PLine(HarborProgress.Expeditions[p.expedition]+" / "+left/60+"m "+left%60+"s remaining",y);y+=38;if(PButton("COLLECT CARGO",y,left==0))Act(()=>HarborProgress.Collect(p,now));y+=40;}for(int i=0;i<3;i++){int id=i;Text(HarborProgress.Expeditions[i],5,y,367,22,19);y+=25;PLine(HarborProgress.Seconds[i]/60+" minutes / Ferry level "+(i+1),y);y+=25;PLine(HarborProgress.Materials(HarborProgress.Cargo[i]),y);y+=30;if(PButton("SEND CREW",y,p.expedition<0&&p.build[1]>=i+1))Act(()=>HarborProgress.Dispatch(p,id,now));y+=45;}}
 if(progressionPage==6){for(int i=0;i<3;i++){int id=i;Text(HarborProgress.Captains[i],5,y,367,23,20);y+=28;PLine(EncounterModel.Routes[i]+" / stretch "+((i+1)*5)+" or later",y);y+=30;PLine("First clear: "+HarborProgress.Materials(HarborProgress.CaptainRewards[i]),y);y+=35;PLine(i==0?"Workshop permit and district pennant":i==1?"District beacon and one attachment rank":"District monument and 100 XP per weapon",y);y+=35;PLine(p.district[i]?"RECLAIMED":"Not yet reclaimed",y);y+=25;if(PButton("TRAVEL TO DISTRICT",y,m.Best>=i*5&&!m.UltimateActive&&m.State!=EncounterState.Defeat))Act(()=>m.ChooseRoute(id));y+=45;}}
 GUI.EndScrollView();
 }
 }
}
