using UnityEngine;
using System;
namespace BrineGame {
 public sealed class SamuraiFormVisuals:MonoBehaviour {
  SamuraiData data;Sprite[][] frames,hands;Texture2D[] textures;Sprite weaponSprite;SpriteRenderer body,weapon,hand;
  SpriteRenderer Part(string name,int order){var r=new GameObject(name).AddComponent<SpriteRenderer>();r.transform.SetParent(transform,false);r.sortingOrder=order;return r;}
  public void Build(){data=JsonUtility.FromJson<SamuraiData>(Resources.Load<TextAsset>("samurai-animation").text);frames=new Sprite[data.clips.Length][];hands=new Sprite[data.clips.Length][];textures=new Texture2D[data.clips.Length];for(int i=0;i<data.clips.Length;i++){var c=data.clips[i];var tex=textures[i]=SamuraiPreview.PrepareEyes(Resources.Load<Texture2D>("samurai-"+c.name),c.name=="walk"?Resources.Load<Texture2D>("samurai-walk-original"):null,c);frames[i]=new Sprite[c.frames.Length];hands[i]=new Sprite[c.frames.Length];for(int j=0;j<c.frames.Length;j++){var f=c.frames[j];frames[i][j]=Sprite.Create(tex,new Rect(f.x,tex.height-f.y-f.h,f.w,f.h),new Vector2(f.anchorX/f.w,1-f.anchorY/f.h),100,0,SpriteMeshType.FullRect);hands[i][j]=Sprite.Create(tex,new Rect(f.x+f.gripX-10,tex.height-f.y-f.gripY-9,20,18),new Vector2(.5f,.5f),100,0,SpriteMeshType.FullRect);}}
   var w=data.weapon;var image=Resources.Load<Texture2D>("samurai-katana");weaponSprite=Sprite.Create(image,new Rect(0,0,image.width,image.height),new Vector2(w.gripX/image.width,1-w.gripY/image.height),100,0,SpriteMeshType.FullRect);body=Part("Samurai body",10);weapon=Part("Breakwater sword",11);hand=Part("Sword grip fingers",12);weapon.sprite=weaponSprite;
  }
  public void Render(EncounterModel m,bool show){body.enabled=weapon.enabled=hand.enabled=show;if(!show)return;bool moving=m.MeleeWalking||m.MeleeIdleActive,attacking=!moving&&m.MeleeCycle>0&&m.MeleeCycle<m.Settings.meleeDuration;string name=moving?"walk":attacking&&m.MeleeAttackIndex%2==1?"series":"slash";int ci=Array.FindIndex(data.clips,c=>c.name==name);var clip=data.clips[ci];int frame=0;if(moving)frame=Mathf.FloorToInt((m.MeleeIdleActive?m.MeleeIdleTime:m.MeleeWalkTime)*18)%20;else if(attacking){int impact=name=="slash"?6:15;float t=m.MeleeCycle;frame=t<m.Settings.meleeImpact?Mathf.FloorToInt(t/m.Settings.meleeImpact*impact):Mathf.Min(clip.frames.Length-1,impact+Mathf.FloorToInt((t-m.Settings.meleeImpact)/(m.Settings.meleeDuration-m.Settings.meleeImpact)*(clip.frames.Length-impact)));}var f=clip.frames[frame];float k=145f/360*clip.scale;body.sprite=frames[ci][frame];body.transform.position=BrineGameController.World(124+m.MeleeAdvance,572);body.transform.localScale=Vector3.one*k;var grip=BrineGameController.World(124+m.MeleeAdvance+(f.gripX-f.anchorX)*k,572+(f.gripY-f.anchorY)*k);weapon.transform.position=hand.transform.position=grip;weapon.transform.localRotation=Quaternion.Euler(0,0,-f.angle);weapon.transform.localScale=Vector3.one*(data.weapon.scale*145/360);hand.sprite=hands[ci][frame];hand.transform.localScale=Vector3.one*k;
  }
  void OnDestroy(){if(frames!=null)foreach(var clip in frames)foreach(var s in clip)Destroy(s);if(hands!=null)foreach(var clip in hands)foreach(var s in clip)Destroy(s);if(textures!=null)foreach(var t in textures)Destroy(t);if(weaponSprite)Destroy(weaponSprite);}
 }
}
