const assert=require('node:assert/strict');
const {Encounter}=require('../web/combat-v3.js'),P=require('../web/progression.js'),J=require('../web/journey.js'),F=require('../web/tideglass.js'),settings=require('../web/gameplay.json');J.install(Encounter,P);F.install(Encounter,P,J);
function model(){const m=new Encounter(settings);m.best=1000000;m.stage=1000000;m.xp=30000;m.gold=1e30;m.forge.tideglass=1e12;return m;}
for(const rank of [30,100,1000,100000]){const m=model();for(const k of Object.keys(m.upgrades)){m.upgrades[k]=Math.min(rank,m.cap(k));if(!Number.isFinite(m.cap(k))){const price=m.cost(k),before=m.upgradeValue(k);assert(Number.isFinite(price)&&price>0);assert(m.buy(k));assert(m.upgradeValue(k)>before,k+' stays useful at '+rank);}}m.playerHp=m.maxPlayerHp;m.startEncounter();assert(Number.isFinite(m.damage));assert(m.interval>=.08);assert(m.reward>0);assert(m.recoveryPercent<100);assert(m.chargePerHit<100);const n=model();assert(n.load(m.save(1000),1000));assert.equal(n.best,1000000);assert.deepEqual(n.upgrades,m.upgrades);assert.equal(n.gold,m.gold);assert.equal(n.playerHp,m.playerHp);}
const m=model();m.upgrades.focus=100;m.upgrades.rupture=30;assert(!m.buy('focus'));assert(!m.buy('rupture'));m.startEncounter();m.state='fight';m.hp=m.maxHp=1e9;m.hitEnemy(100,'scrap',460);assert.equal(m.maxHp-m.hp,500,'200% chance + 300% crit damage makes a guaranteed double-tier 5x hit');
m.forge.overclock.power=100;assert(m.buyOverclock('power'));assert.equal(m.forge.overclock.power,101);
const a=model();a.stage=100000;a.startEncounter();const low=a.maxHp,lowReward=a.reward;a.stage=1000000;a.startEncounter();assert(a.maxHp>low&&a.reward>lowReward);
const costs=[29,30,31,100,1000].map(r=>{a.upgrades.damage=r;return a.cost('damage')});assert(costs.every((v,i)=>!i||v>costs[i-1]));assert(F.format(1e24).length<12);
console.log('PASS: uncapped rank purchases, useful gains through 100k, million-stage saves, bounded combat rates, two-tier crits, endless Overclock, increasing rewards and costs.');
