const assert=require('node:assert/strict'),fs=require('fs');
const {Encounter,enemies}=require('../web/combat-v3.js'),settings=require('../web/gameplay.json');
const origin={x:215,y:500};
function battle(stage=1){const m=new Encounter(settings);m.stage=stage;m.best=stage-1;m.startEncounter();for(let i=0;i<600&&m.state!=='fight';i++)m.tick(.02,origin);assert.equal(m.state,'fight');m.hp=m.maxHp=10000;return m;}
let m=battle();assert(!m.ultimate());m.ultimateCharge=100;m.charge=100;assert(m.ultimate());assert(!m.ultimate());assert(!m.volley());const gun=m.weapon,hp=m.playerHp;m.enemyShots=[{x:146,y:500,damage:40}];m.tick(.02,origin);assert.equal(m.playerHp,hp-10,'75% resistance');
for(let i=0;i<62;i++)m.tick(.02,origin);assert.equal(m.hp,10000-m.damage*4,'melee hits for 4x');assert.equal(m.shots.length,0);assert.equal(m.ultimateCharge,0,'no self-charging ultimate');assert(m.meleeAdvance>0&&m.meleeAdvance<=m.meleeReach);m.paused=true;const frozen=JSON.stringify(m);m.tick(.1,origin);assert.equal(JSON.stringify(m),frozen);m.paused=false;m.enemyShots=[];m.enemyCycle=-100;
for(let i=0;i<400;i++)m.tick(.02,origin);assert(!m.ultimateActive);assert.equal(m.weapon,gun);for(let i=0;i<70;i++)m.tick(.02,origin);assert(m.shotSerial>0,'gun resumes');assert(m.meleeAdvance<.01,'returns to lane');
m=battle(3);assert.equal(m.enemy.action,'guard');m.hitEnemy(100,'scrap',500);assert.equal(m.hp,9965);m.hitEnemy(100,'melee',500);assert.equal(m.hp,9865);
m=battle(6);assert.equal(m.enemy.action,'burrow');m.enemyCycle=m.enemy.interval*.5;m.hitEnemy(100,'scrap',500);assert.equal(m.hp,10000);m.hitEnemy(100,'melee',500);assert.equal(m.hp,9900);
m=battle(4);m.hp=5000;m.enemyCycle=m.enemy.interval-.01;m.cycle=-100;m.tick(.02,origin);assert.equal(m.hp,6200,'repair resolves after tell');
m=battle(2);m.enemyCycle=m.enemy.interval-.01;m.cycle=-100;m.tick(.02,origin);assert.equal(m.enemyShots.length,3,'burst enemy');
m=battle();assert(!m.chooseRoute(1));m.best=10;const baseReward=m.reward,baseDamage=m.enemyDamage;assert(m.chooseRoute(2));assert.equal(m.reward,Math.floor(baseReward*1.5));assert.equal(m.enemyDamage,Math.round(baseDamage*1.45));m.gold=1000;assert(m.buyMod());assert.equal(m.damage,17);assert(m.equip('repeater'));assert.equal(m.modRank,0,'per-weapon mods');m.buyMod();m.buyMod();m.buyMod();assert(!m.buyMod());m.ultimateCharge=83;
const saved=m.save(1000),copy=new Encounter(settings);copy.load(saved,1000);assert.deepEqual(copy.save(1000),saved,'new progression roundtrip');const old={...saved};delete old.mods;delete old.ultimateCharge;delete old.route;assert(copy.load(old,1000));assert.equal(copy.modRank,0);assert.equal(copy.ultimateCharge,0);assert.equal(copy.route,0);
assert.equal(new Set(Array.from({length:10},(_,i)=>{m.stage=i+1;return m.enemy.name})).size,6,'all six types in first ten stretches');
const layers=require('../web/parallax.json').layers;assert(layers.length>=4);assert(layers.some(l=>l.speed===0)&&layers.some(l=>l.speed>1));for(const l of layers){assert(l.period>=450);for(const d of [0,499,9999]){const offset=d*l.speed%l.period;assert(-offset<=0&&2*l.period-offset>=450,'repeat coverage');}for(const s of l.shapes)assert(s.points.length>=3);}
assert.deepEqual(require('../web/parallax.json'),JSON.parse(fs.readFileSync('unity/BrineAgainstTheWorld/Assets/Brine/Resources/parallax.json')));
console.log('PASS: melee/resistance/expiry/pause, weapon restoration, no Ultimate recharge exploit, guard/burrow counters, repair/burst actions, route rewards/locks, per-gun mods, save migration, six enemies, shared parallax coverage.');
