const assert=require('node:assert/strict'),{Encounter}=require('../web/combat-v3.js'),P=require('../web/progression.js'),J=require('../web/journey.js'),F=require('../web/tideglass.js'),B=require('../web/build-upgrades.js'),R=require('../web/reforge.js'),S=require('../web/scrapyard.js'),T=require('../web/pacing.js'),Speed=require('../web/battle-speed.js'),settings=require('../web/gameplay.json');J.install(Encounter,P);F.install(Encounter,P,J);B.install(Encounter,P,J,F);R.install(Encounter);S.install(Encounter);T.install(Encounter);
function setup(){const m=new Encounter(settings);m.best=2914;m.stage=2915;m.gold=58000000;m.xp=30*62**2;m.upgrades.damage=60;m.upgrades.shell=60;m.upgrades.speed=60;m.upgrades.focus=100;m.upgrades.rupture=30;m.upgrades.patch=20;m.upgrades.plating=20;m.upgrades.scavenging=40;m.weapon='boiler';m.mods.boiler=3;m.reforges.boiler=2;m.forge.tideglass=635;m.forge.overclock.power=10;m.shop.owned=['shell:deep','mod:duck'];m.shop.shell='deep';m.shop.mods.boiler='duck';m.playerHp=m.maxPlayerHp;m.startEncounter();return m;}
assert.equal(T.compact(2915),500);assert.equal(T.compact(2914,true),499);assert.equal(T.expand(500),2915);assert.equal(T.compact(50),50);
const m=setup(),before=m.save(1000);assert(m.tryPacing());assert.equal(m.stage,500);assert.equal(m.best,499);assert.equal(m.gold,58000000);assert.equal(m.forge.tideglass,635);assert.deepEqual(m.upgrades,before.upgrades);assert.deepEqual(m.mods,before.mods);assert.deepEqual(m.reforges,before.reforges);assert.deepEqual(m.shop,before.shop);assert(!m.tryPacing());assert.equal(m.unlockStage(1000),200);
const health=m.maxHp;m.upgrades.damage+=10;m.startEncounter();assert.equal(m.maxHp,health,'Enemies do not auto-scale after upgrades');m.upgrades.damage-=10;
const saved=m.save(1000),loaded=setup();assert(loaded.load(saved,1000));assert.equal(loaded.stage,500);assert.equal(loaded.maxHp,m.maxHp);assert.equal(loaded.gold,m.gold);assert(loaded.leavePacing());assert.equal(loaded.stage,2915);assert.equal(loaded.best,2914);assert.equal(loaded.gold,58000000);loaded.gold+=123;assert(loaded.tryPacing());assert.equal(loaded.gold,58000123);assert.equal(loaded.pacing.dps,m.pacing.dps,'Re-entry retains calibration');
const dead=m.save(1000);dead.defeated=true;dead.playerHp=0;loaded.load(dead,1000);assert.equal(loaded.state,'defeat');
const campaign=setup();campaign.tryPacing();assert(campaign.enterCampaign(0,1));assert(!campaign.leavePacing());assert.equal(campaign.maxHp,Math.round((settings.enemyHealth+(campaign.stage-1)*9)*campaign.enemy.health));assert.equal(campaign.enemyRepairFraction,.12);campaign.leaveCampaign();assert(campaign.pacing.enabled);
function battle(data,stage,speed){const a=setup();a.load(data,data.savedAt);a.stage=stage;a.startEncounter();a.playerHp=a.maxPlayerHp;const baseKills=a.kills,baseGold=a.gold,step=Speed.stepper();let wall=0,fight=0;for(;wall<180&&a.kills===baseKills&&a.state!=='defeat';wall+=1/60){if(a.state==='fight')fight+=1/60;step.advance(1/60,speed,a,()=>({x:200,y:460}));}return {stage,speed,fight:+fight.toFixed(2),wall:+wall.toFixed(2),outcome:a.kills>baseKills?'win':a.state,gold:a.gold-baseGold};}
const rows=[];for(const stage of [496,497,498,499,500])for(const speed of [1,3]){const row=battle(saved,stage,speed);assert.equal(row.outcome,'win');rows.push(row);}
const normal=rows.filter(r=>r.stage!==500&&r.speed===1);assert(normal.every(r=>r.fight>2&&r.fight<16));assert(rows.find(r=>r.stage===500&&r.speed===1).fight>15);for(const stage of [496,497,498,499,500]){const one=rows.find(r=>r.stage===stage&&r.speed===1),three=rows.find(r=>r.stage===stage&&r.speed===3);assert(Math.abs(one.wall/3-three.wall)<.1);}
console.log('PASS: reversible compaction, wallets/ownership, frozen calibration, save/load, campaign isolation and 1x/3x timing');console.log(JSON.stringify({calibration:m.pacing,rows}));
