const assert=require('node:assert/strict'),P=require('../web/progression.js'),{Encounter}=require('../web/combat-v3.js');
const p=P.fresh();assert(!P.build(p,0));assert(!P.dispatch(p,0,1000));assert(!P.chooseWeapon(p,'scrap','impact'));assert(!P.chooseForm(p,'samurai','flow'));
const m=new Encounter();m.stage=5;m.startEncounter();m.state='fight';m.hp=1;m.hitEnemy(100,'scrap',500);assert(m.progress.district[0]);assert.equal(m.progress.materials[1],9);const first=[...m.progress.materials];m.state='fight';m.hp=1;m.hitEnemy(100,'scrap',500);assert.deepEqual(m.progress.materials,first.map((x,i)=>x+(i===0?1:i===1?3:0)),'Repeat captain grants ordinary loot only');assert(P.build(m.progress,0));assert.equal(m.progress.build[0],1);
P.award(p,[10000,10000,10000]);p.district[0]=true;for(let b=0;b<3;b++){for(let i=0;i<3;i++)assert(P.build(p,b));const before=[...p.materials];assert(!P.build(p,b));assert.deepEqual(p.materials,before);}
assert(P.dispatch(p,0,1000));assert(!P.dispatch(p,1,1000));assert(!P.collect(p,180999));const saved=P.load(JSON.parse(JSON.stringify(p)));assert(P.collect(saved,181000));const cargo=[...saved.materials];assert(!P.collect(saved,999999));assert.deepEqual(saved.materials,cargo);assert(P.dispatch(saved,2,999999));assert(!P.collect(saved,1),'Clock rollback cannot complete a future expedition');
const c=new Encounter();for(let i=0;i<12;i++){c.state='fight';c.hp=1;c.hitEnemy(100,'scrap',500);}assert.equal(c.progress.counts[0],12);assert(P.claimContract(c.progress));assert(!P.claimContract(c.progress));assert(P.selectContract(c.progress,'shell'));c.state='fight';c.hp=1;c.hitEnemy(100,'scrap',500);assert.equal(c.progress.counts[1],0);c.selectedForm='step-shell';c.state='fight';c.hp=1;c.hitEnemy(100,'melee',500);assert.equal(c.progress.counts[1],1);assert(P.selectContract(c.progress,'road'));assert(P.selectContract(c.progress,'shell'));assert.equal(c.progress.counts[1],1);
const gun=new Encounter();gun.progress.build[0]=1;gun.progress.weaponXP[0]=20;assert(P.chooseWeapon(gun.progress,'scrap','pierce'));gun.stage=3;gun.startEncounter();gun.state='fight';gun.hp=1000;const hp=gun.hp;gun.hitEnemy(100,'scrap',500);assert.equal(hp-gun.hp,100,'Piercing bypasses active guard');
const form=new Encounter();form.progress.build[2]=1;form.progress.formXP[1]=12;assert(P.chooseForm(form.progress,'samurai','flow'));form.selectedForm='samurai';form.ultimateTime=5;form.state='fight';form.hp=999;form.hitEnemy(10,'melee',500);assert.equal(form.ultimateCharge,3);
form.progress.formPath[1]='execute';form.maxHp=1000;form.hp=300;form.hitEnemy(10,'melee',500);assert.equal(form.hp,285);
const snapshot=form.save(1000),restored=new Encounter();assert(restored.load(snapshot,1000));assert.deepEqual(restored.progress, P.load(snapshot.progress));form.progress.materials[0]++;assert.notEqual(snapshot.progress.materials[0],form.progress.materials[0]);
const malformed=P.load({version:1,build:[999,-4,'bad'],materials:[-1,Infinity,5],weaponPath:['bad'],expedition:{id:99,finish:1}});assert.deepEqual(malformed.build,[3,0,0]);assert.deepEqual(malformed.materials,[0,0,5]);assert.equal(malformed.expedition,null);assert.equal(malformed.weaponPath[0],'');
const legacy=new Encounter();const old=legacy.save(0);delete old.progress;assert(legacy.load(old,0));assert.deepEqual(legacy.progress.materials,[0,0,0]);
for(let route=0;route<3;route++){const boss=new Encounter();boss.route=route;boss.stage=(route+1)*5;boss.startEncounter();boss.state='fight';boss.hp=1;boss.hitEnemy(10000,'melee',500);assert(boss.progress.district[route]);assert.equal(boss.enemy.name,P.captains[route].name);}
console.log('PASS: captain one-time rewards, capped restoration costs, contracts and selection retention, mastery guard bypass, form flow/finisher effects, offline crew completion/no duplicate claims, malformed and legacy saves, snapshot isolation, all district unlocks.');


const veteran=new Encounter(),oldSave=veteran.save(1000);delete oldSave.progress;oldSave.best=5;oldSave.stage=6;assert(veteran.load(oldSave,1000));assert(veteran.progress.district[0]);assert.deepEqual(veteran.progress.materials,P.captains[0].reward);const inherited=veteran.save(1000);assert(veteran.load(inherited,1000));assert.deepEqual(veteran.progress.materials,P.captains[0].reward,'Legacy clear credited only once');
const impact=new Encounter();impact.progress.build[0]=1;impact.progress.weaponXP[0]=140;P.chooseWeapon(impact.progress,'scrap','impact');assert.equal(P.hit(impact,100,'scrap'),175);
const tempo=new Encounter();tempo.weapon='repeater';const baseInterval=tempo.interval;tempo.progress.build[0]=1;tempo.progress.weaponXP[1]=140;P.chooseWeapon(tempo.progress,'repeater','tempo');assert(tempo.interval<baseInterval);
const shatter=new Encounter();shatter.progress.build[0]=1;shatter.progress.weaponXP[2]=140;P.chooseWeapon(shatter.progress,'lowtide','shatter');P.hit(shatter,10,'lowtide');assert.equal(shatter.shattered,.24);shatter.startEncounter();assert.equal(shatter.shattered,0);
const mend=new Encounter();mend.progress.build[2]=1;mend.progress.formXP[0]=12;P.chooseForm(mend.progress,'step-shell','mend');mend.playerHp=50;P.hit(mend,10,'melee');assert.equal(mend.playerHp,52);
const guard=new Encounter();guard.progress.build[2]=1;guard.progress.formXP[0]=12;P.chooseForm(guard.progress,'step-shell','bastion');guard.state='fight';guard.ultimateTime=5;guard.enemyShots=[{x:0,y:500,damage:100}];guard.tick(.01,{x:215,y:500});assert.equal(guard.playerHp,85);
const guide=new Encounter();guide.progress.guide[0]=15;assert(Math.abs(P.hit(guide,100,'scrap')-110)<1e-8);
console.log('PASS: impact, tempo, shatter expiry, living armor, bastion resistance, and researched-enemy combat effects.');
