(function(root){
'use strict';
function install(C,J,S){if(C.prototype.captainToolsInstalled)return;C.prototype.captainToolsInstalled=true;
const reset=C.prototype.reset;C.prototype.reset=function(){this.savedKits=[null,null,null];this.combatLog=[];this.intelFight=null;reset.call(this);};
const start=C.prototype.startEncounter;C.prototype.startEncounter=function(){start.call(this);this.intelFight={enemy:this.enemy.name,stage:this.stage,seconds:0,damage:0,done:false};};
C.prototype.enemyIntel=function(){const e=this.enemy,notes=[];if(this.lowTideTime>0)notes.push('Form exhaustion: gun damage is reduced until recovery ends.');if(e.action==='guard')notes.push('Armored target: guard reduces ordinary gun hits. Keelspike bypasses guard; melee also bypasses it.');if(e.action==='repair')notes.push('Repair crew: it restores health during battle. Save Volley for REPAIR INCOMING to interrupt and open a damage window.');if(e.action==='burrow')notes.push('Burrowing target: gun shots miss while submerged. Melee can still connect.');if(this.forge?.run?.challenge===2)notes.push('Swarm challenge: Rivet Rattle, Tideline and Low Tide gain bonus damage.');if(this.boss)notes.push('Captain: watch for HEAVY ATTACK. Step Shell reduces incoming damage; strike during the opening afterward.');if((this.intelFight?.seconds||0)>20)notes.push('Long fight: compare your weapon upgrades and damage ranks in Build.');return notes.length?notes:['No special defense detected. Improve damage for quicker clears, or shell and recovery if you are losing health.'];};
C.prototype.finishCombatReport=function(f,outcome){if(!f||f.done)return;f.done=true;this.combatLog.unshift({enemy:f.enemy,stage:f.stage,seconds:f.seconds,damage:f.damage,outcome,advice:f.advice||this.enemyIntel()[0]});this.combatLog.length=Math.min(10,this.combatLog.length);};
const hit=C.prototype.hitEnemy;C.prototype.hitEnemy=function(...args){const f=this.intelFight,hp=this.hp,kills=this.kills,outer=!this.intelHitDepth;if(outer&&f&&!f.done)f.advice=this.enemyIntel()[0];this.intelHitDepth=(this.intelHitDepth||0)+1;let result;try{result=hit.apply(this,args);}finally{this.intelHitDepth--;}if(outer&&f&&!f.done){f.damage+=Math.max(0,hp-(this.kills>kills?0:this.hp));if(this.kills>kills)this.finishCombatReport(f,'Victory');}return result;};
const tick=C.prototype.tick;C.prototype.tick=function(dt,...args){const f=this.intelFight,active=!this.paused&&this.state==='fight';if(active&&f&&!f.done)f.seconds+=dt;const result=tick.call(this,dt,...args);if(active&&this.state==='defeat')this.finishCombatReport(f,'Defeat');return result;};
C.prototype.saveKit=function(slot){if(!Number.isInteger(slot)||slot<0||slot>2)return false;this.savedKits[slot]={weapon:this.weapon,form:this.selectedForm,mod:this.shop.mods[this.weapon]||'none'};return true;};
C.prototype.kitAvailable=function(k){return !!k&&this.settings.weapons.some(w=>w.id===k.weapon&&this.best>=w.unlock)&&J.available(this,k.weapon)&&['step-shell','samurai'].includes(k.form)&&(k.form===this.selectedForm||J.available(this,k.form))&&(k.mod==='none'||S.mods.some(m=>m.id===k.mod)&&this.shop.owned.includes('mod:'+k.mod));};
C.prototype.applyKit=function(slot){if(!Number.isInteger(slot)||slot<0||slot>2||this.ultimateActive)return false;const k=this.savedKits[slot];if(!this.kitAvailable(k))return false;const previous=this.weapon;if(!this.equip(k.weapon))return false;if(k.form!==this.selectedForm&&!this.chooseForm(k.form)){this.weapon=previous;return false;}this.shopEquip('mod',k.mod);return true;};
const save=C.prototype.save;C.prototype.save=function(...args){return {...save.apply(this,args),savedKits:this.savedKits.map(k=>k?{...k}:null)};};
const load=C.prototype.load;C.prototype.load=function(data,...args){const ok=load.call(this,data,...args);if(!ok)return ok;this.savedKits=[0,1,2].map(i=>{const k=data.savedKits?.[i];return k&&this.settings.weapons.some(w=>w.id===k.weapon)&&['step-shell','samurai'].includes(k.form)&&(k.mod==='none'||S.mods.some(m=>m.id===k.mod))?{weapon:k.weapon,form:k.form,mod:k.mod}:null;});this.combatLog=[];return ok;};
}
const api={install};if(typeof module!=='undefined')module.exports=api;else{root.BrineCaptainTools=api;install(root.BrineCombat.Encounter,root.BrineJourney,root.BrineShop);}
})(typeof globalThis!=='undefined'?globalThis:this);
