let progressRenderTarget=null;
const progressContent=()=>progressRenderTarget||$('progress-content');
const escapeHarbor=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const P=BrineProgression;let progressTab='harbor',progressKey='';
const labels={harbor:'Harbor',contracts:'Contracts',mastery:'Weapons',forms:'Forms',guide:'Field guide',expeditions:'Expeditions',districts:'Districts'};
$('progress-tabs').innerHTML=Object.entries(labels).map(([id,label])=>`<button data-progress-tab="${id}">${label}</button>`).join('');
$('next-goal').onclick=()=>{if(typeof comicReady!=='undefined'&&comicReady.length){openComicReward(comicReady[0].tab);return;}const index=P.contracts.findIndex(c=>c.id===model.progress.contract);progressTab=model.progress.counts[index]>=P.contracts[index].target?'contracts':'harbor';openHarbor('camp');progressKey='';refreshProgressionUI()};
$('progress-tabs').onclick=e=>{const b=e.target.closest('[data-progress-tab]');if(b){progressTab=b.dataset.progressTab;progressKey='';refreshProgressionUI()}};
const cargo=a=>a.map((v,i)=>v?`${v} ${['timber','brass','charts'][i]}`:'').filter(Boolean).join(' · ');
const meter=(v,max)=>`<div class="progress-meter"><i style="width:${Math.min(100,v/max*100)}%"></i><span>${Math.min(v,max)} / ${max}</span></div>`;
const card=(title,body)=>`<article class="goal-card"><h3>${title}</h3>${body}</article>`;
const action=(text,act,arg='',disabled=false)=>`<button data-progress-action="${act}" data-value="${arg}" ${disabled?'disabled':''}>${text}</button>`;
function refreshProgressionUI(){const p=model.progress;if(!p)return;const c=P.contracts.find(c=>c.id===p.contract),ci=P.contracts.indexOf(c);const ready=!p.finishedContracts?.includes(c.id)&&p.counts[ci]>=c.target;const detail=ready?'Contract complete · tap to collect':P.next(p);$('goal-eyebrow').textContent=ready?'REWARD READY':'NEXT GOAL';$('goal-detail').textContent=detail;$('next-goal').dataset.ready=ready;$('next-goal').setAttribute('aria-label',(ready?'Open contract reward: ':'Open harbor goals: ')+detail);if(typeof refreshComicNotifications==='function')refreshComicNotifications();const key=JSON.stringify([p,progressTab,model.best,model.ultimateActive,progressTab==='expeditions'?Math.floor(Date.now()/1000):0]);if($('drawer').hidden||harborTab!=='camp'||key===progressKey)return;progressKey=key;$('next-goal').title=P.next(p)+' · '+c.name+': '+p.counts[ci]+'/'+c.target;for(const b of $('progress-tabs').children)b.setAttribute('aria-pressed',b.dataset.progressTab===progressTab);
let html=`<p class="cargo">${cargo(p.materials)||'No materials yet · every win earns timber'}</p><p class="harbor-notice" role="status">${escapeHarbor(p.notice||'Choose a project and reclaim the harbor.')}</p>`;
if(progressTab==='harbor'){html+=harborDrawing(p)+card('Next unlock',`<p>${P.next(p)}</p>`);html+=P.buildings.map((b,i)=>{const cost=P.buildCost(p,i),max=p.build[i]===3;return card(`${b.name} · ${p.build[i]} / 3`,`${harborBuildingArt(i,p.build[i],'100%',150)}<p>${max?'Fully restored':b.detail[p.build[i]]}</p>${meter(p.build[i],3)}<p>${max?'Complete':!p.district[0]?'Requires Foreman Rusk’s permit':cargo(cost)}</p>${action(max?'Restored':'Restore / improve','build',i,max||!p.district[0]||cost.some((v,j)=>p.materials[j]<v))}`)}).join('');}
if(progressTab==='contracts')html+='<p>Choose one active contract. Switching keeps earned progress. No timers or streak penalties.</p>'+P.contracts.map((c,i)=>card(c.name+(p.counts[i]>=c.target?' <span class="task-ready" aria-label="Reward ready">!</span>':''),`<p>${c.description}</p>${meter(p.finishedContracts?.includes(c.id)?c.target:p.counts[i],c.target)}<p>Reward: ${cargo(c.reward)}</p>${p.finishedContracts?.includes(c.id)?'<p>COMPLETED · reward collected</p>'+action('↻ Repeat contract','contract',c.id):p.contract===c.id?action(p.counts[i]>=c.target?'Collect reward':'Tracking','claim','',p.counts[i]<c.target):action('Track contract','contract',c.id)}`)).join('');
if(progressTab==='mastery')html+='<p>Weapon branches: restore the Workshop and land 20 gun hits to choose one path per gun. Branches strengthen at 60 and 140 hits. Switch freely between transformations.</p>'+P.ids.map((id,i)=>{const t=P.tier(p.weaponXP[i]);return card(model.settings.weapons.find(w=>w.id===id).name+` · tier ${t}/3`,`<p>${p.weaponXP[i]} XP · tiers at 20 / 60 / 140 hits</p>${meter(p.weaponXP[i],t===0?20:t===1?60:140)}${P.paths[id].map(([path,name,desc])=>`<p><b>${name}</b> — ${desc}</p>${action(p.weaponPath[i]===path?'Equipped':name,'weapon',id+':'+path,!p.build[0]||!t||model.ultimateActive||p.weaponPath[i]===path)}`).join('')}`)}).join('');
if(progressTab==='forms')html+='<p>Melee contacts earn form practice. Restore the Lighthouse and land 12 contacts to specialize.</p>'+P.forms.map((id,i)=>card(id==='samurai'?'Samurai':'Step Shell',`${meter(p.formXP[i],12)}${P.formPaths[id].map(([path,name,desc])=>`<p><b>${name}</b> — ${desc}</p>${action(p.formPath[i]===path?'Equipped':name,'form',id+':'+path,!p.build[2]||p.formXP[i]<12||model.ultimateActive||p.formPath[i]===path)}`).join('')}`)).join('');
if(progressTab==='guide'){const tips={lob:'Lobs a heavy projectile. Shell upgrades help absorb it.',burst:'Fires a rapid three-shot burst.',slam:'A slow, heavy strike; build shell before pushing.',guard:'Raises a shield. Melee and piercing paths bypass it.',repair:'Repairs 12% health at each attack. Burst damage helps.',burrow:'Burrows underground. Gunfire misses; melee still connects.'};html+='<p>3 defeats reveal tactics. 15 defeats permanently grant +10% damage against that enemy.</p>'+BrineCombat.enemies.map((e,i)=>card(e.name,`<img class="guide-portrait" src="enemies/${e.art}.png" alt="${e.name}">${meter(p.guide[i],15)}<p>${p.guide[i]>=3?tips[e.action]:'Tactics unlock after 3 defeats.'}</p><p>${p.guide[i]>=15?'Studied · +10% damage':'Defeated '+p.guide[i]+' times'}</p>`)).join('');}
if(progressTab==='expeditions'){html+='<p>One crew, guaranteed cargo. Expeditions continue while the game is closed. Collect once when they return.</p>';if(p.expedition){const e=P.expeditions[p.expedition.id],seconds=Math.max(0,Math.ceil((p.expedition.finish-Math.max(Date.now(),p.clock))/1000));html+=card(e.name,`<p>${seconds?Math.floor(seconds/60)+'m '+seconds%60+'s remaining':'Crew returned'}</p><p>${cargo(e.reward)}</p>${action('Collect cargo','collect','',seconds>0)}`);}html+=P.expeditions.map((e,i)=>card(e.name,`<p>${e.seconds/60} minutes · requires Ferry level ${e.level}</p><p>Guaranteed: ${cargo(e.reward)}</p>${action('Send crew','dispatch',i,!!p.expedition||p.build[1]<e.level)}`)).join('');}
if(progressTab==='districts')html+=P.captains.map((c,i)=>card(c.name+` · ${BrineCombat.routes[i].name}`,`<img class="guide-portrait" src="enemies/${c.art}.png" alt="Captain ${c.name}"><p>Defeat this captain on ${BrineCombat.routes[i].name} at stretch ${c.stage} or later.</p><p>First clear: ${cargo(c.reward)} · ${c.unlock}</p><p>${p.district[i]?'DISTRICT RECLAIMED · REWARDS RECEIVED':'Not yet reclaimed'}</p>${action('Travel to district','route',i,model.best<i*5||model.ultimateActive||model.state==='defeat')}`)).join('');
BrineUI.patch(progressContent(),html);}
$('progress-content').onclick=e=>{const b=e.target.closest('[data-progress-action]');if(!b||b.disabled)return;const a=b.dataset.progressAction,v=b.dataset.value,p=model.progress;let ok=false;if(a==='build')ok=P.build(p,+v);if(a==='contract')ok=P.selectContract(p,v);if(a==='claim')ok=P.claimContract(p);if(a==='weapon'&&!model.ultimateActive)ok=P.chooseWeapon(p,...v.split(':'));if(a==='form'&&!model.ultimateActive)ok=P.chooseForm(p,...v.split(':'));if(a==='dispatch')ok=P.dispatch(p,+v,Date.now());if(a==='collect')ok=P.collect(p,Date.now());if(a==='route')ok=model.chooseRoute(+v);if(ok){persist();progressKey='';refresh();}};
