(function(root){
'use strict';
const ids=['scrap','repeater','lowtide'],forms=['step-shell','samurai'],foes=['salt-porter','pipe-pilfer','sluice-keeper','gate-hauler','sump-mender','mud-skipper'];
const buildings=[{id:'workshop',name:'Workshop',unlock:'Weapon mastery paths',cost:[12,3,0],detail:['Mastery paths open','+5% weapon damage','+10% weapon damage']},{id:'ferry',name:'Ferry Dock',unlock:'Crew expeditions',cost:[18,4,0],detail:['Short expeditions open','Chart expeditions open','Deep salvage expeditions open']},{id:'lookout',name:'Lighthouse',unlock:'Form specializations',cost:[24,6,1],detail:['Form paths open','+5% salvage income','+10% salvage income']}];
const captains=[{name:'Foreman Rusk',stage:5,art:'sluice-keeper',action:'slam',reward:[12,6,1],unlock:'Workshop permit + Dry Docks pennant'},{name:'Valve-Mother Venn',stage:10,art:'sump-mender',action:'repair',reward:[20,9,2],unlock:'Drainage beacon + 1 free attachment rank'},{name:'Marshal Flint',stage:15,art:'gate-hauler',action:'guard',reward:[30,12,3],unlock:'Salt Flats monument + 100 mastery XP per gun'}];
const contracts=[{id:'road',name:'Clear the boards',target:12,reward:[8,2,0],description:'Defeat 12 enemies with any weapon or form.'},{id:'shell',name:'Make some room',target:8,reward:[12,3,0],description:'Win 8 battles with Step Shell melee finishing hits.'},{id:'samurai',name:'Clean cuts',target:8,reward:[12,3,0],description:'Win 8 battles with Samurai melee finishing hits.'},{id:'guard',name:'Gatecrashers',target:4,reward:[10,4,1],description:'Defeat 4 Gate Haulers.'},{id:'captain',name:'Break the blockade',target:2,reward:[10,5,1],description:'Defeat 2 captains on any route.'}];
const expeditions=[{name:'Shore sweep',seconds:180,level:1,reward:[10,2,0]},{name:'Channel survey',seconds:900,level:2,reward:[16,4,2]},{name:'Wreck recovery',seconds:2700,level:3,reward:[30,12,3]}];
const paths={scrap:[['pierce','Hardened slug','Bypass enemy guard.'],['impact','Heavy load','+25% gun damage per mastery tier.']],repeater:[['pierce','Needle rounds','Bypass enemy guard.'],['tempo','Quick feed','15% faster firing per mastery tier.']],lowtide:[['shatter','Hull breaker','Reduce enemy attack damage by 8% per tier for this battle.'],['impact','Powder keg','+25% gun damage per mastery tier.']]};
const formPaths={'step-shell':[['bastion','Bastion','85% damage resistance while transformed.'],['mend','Living armor','Each melee hit restores 2% maximum health.']],samurai:[['execute','Finisher','+50% melee damage below 35% enemy health.'],['flow','Flow','Each melee contact banks 3 charge for the next transformation.']]};
const n=(v,max=1e6)=>Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;
function fresh(){return {version:1,materials:[0,0,0],build:[0,0,0],district:[false,false,false],weaponXP:[0,0,0],weaponPath:['','',''],formXP:[0,0],formPath:['',''],guide:[0,0,0,0,0,0],contract:'road',finishedContracts:[],lastContractClaim:null,counts:[0,0,0,0,0],completed:0,expedition:null,clock:0,notice:'Reclaim the harbor. Your first goal: defeat Foreman Rusk.'};}
function load(raw){const p=fresh();if(!raw||raw.version!==1)return p;for(const [key,len,max] of [['materials',3,1e6],['build',3,3],['weaponXP',3,1e6],['formXP',2,1e6],['guide',6,1e6],['counts',5,100]])p[key]=Array.from({length:len},(_,i)=>n(raw[key]?.[i],max));p.district=Array.from({length:3},(_,i)=>raw.district?.[i]===true);p.weaponPath=ids.map((id,i)=>paths[id].some(x=>x[0]===raw.weaponPath?.[i])?raw.weaponPath[i]:'');p.formPath=forms.map((id,i)=>formPaths[id].some(x=>x[0]===raw.formPath?.[i])?raw.formPath[i]:'');if(contracts.some(c=>c.id===raw.contract))p.contract=raw.contract;p.finishedContracts=contracts.filter(c=>raw.finishedContracts?.includes(c.id)).map(c=>c.id);p.lastContractClaim=contracts.some(c=>c.id===raw.lastContractClaim)?raw.lastContractClaim:null;p.completed=n(raw.completed);p.clock=n(raw.clock,9e15);if(raw.expedition&&Number.isInteger(raw.expedition.id)&&expeditions[raw.expedition.id]&&Number.isFinite(raw.expedition.finish)&&raw.expedition.finish>0)p.expedition={id:raw.expedition.id,finish:n(raw.expedition.finish,9e15)};p.notice=typeof raw.notice==='string'?raw.notice.slice(0,180):next(p);return p;}
function award(p,items){p.materials=p.materials.map((v,i)=>Math.min(1e6,v+items[i]));}
function buildCost(p,i){return buildings[i].cost.map(v=>v*(p.build[i]+1));}
function build(p,i){if(!buildings[i]||p.build[i]>=3||!p.district[0])return false;const cost=buildCost(p,i);if(cost.some((v,j)=>p.materials[j]<v))return false;p.materials=p.materials.map((v,j)=>v-cost[j]);p.build[i]++;p.notice=buildings[i].name+' restored: '+buildings[i].detail[p.build[i]-1];return true;}
function tier(x){return x>=140?3:x>=60?2:x>=20?1:0;}
function chooseWeapon(p,id,path){const i=ids.indexOf(id);if(i<0||!p.build[0]||!tier(p.weaponXP[i])||!paths[id].some(x=>x[0]===path))return false;p.weaponPath[i]=path;return true;}
function chooseForm(p,id,path){const i=forms.indexOf(id);if(i<0||!p.build[2]||p.formXP[i]<12||!formPaths[id].some(x=>x[0]===path))return false;p.formPath[i]=path;return true;}
function selectContract(p,id){if(!contracts.some(c=>c.id===id))return false;p.contract=id;if(p.finishedContracts?.includes(id)){p.finishedContracts=p.finishedContracts.filter(x=>x!==id);p.counts[contracts.findIndex(c=>c.id===id)]=0;p.notice='Repeating '+contracts.find(c=>c.id===id).name+'.';}return true;}
function claimContract(p){const i=contracts.findIndex(c=>c.id===p.contract),c=contracts[i];if(p.finishedContracts?.includes(c.id)||p.counts[i]<c.target)return false;p.counts[i]=0;(p.finishedContracts??=[]).push(c.id);p.lastContractClaim=c.id;p.completed++;award(p,c.reward);p.notice=c.name+' complete. Materials delivered.';return true;}
function now(p,time){p.clock=Math.max(p.clock,n(time,9e15));return p.clock;}
function dispatch(p,id,time){if(!Number.isInteger(id)||!expeditions[id]||p.expedition||p.build[1]<expeditions[id].level)return false;p.expedition={id,finish:now(p,time)+expeditions[id].seconds*1000};return true;}
function collect(p,time){if(!p.expedition||now(p,time)<p.expedition.finish)return false;const e=expeditions[p.expedition.id];award(p,e.reward);p.expedition=null;p.notice=e.name+' returned. Guaranteed cargo collected.';return true;}
function hit(m,damage,weapon){const p=m.progress,w=ids.indexOf(weapon),f=forms.indexOf(m.selectedForm),g=foes.indexOf(m.enemy.art);if(g>=0&&p.guide[g]>=15)damage*=1.1;if(weapon==='melee'){p.formXP[f]=Math.min(1e6,p.formXP[f]+1);if(p.formPath[f]==='execute'&&m.hp/m.maxHp<.35)damage*=1.5;if(p.formPath[f]==='mend')m.playerHp=Math.min(m.maxPlayerHp,m.playerHp+Math.max(1,Math.round(m.maxPlayerHp*.02)));if(p.formPath[f]==='flow')m.ultimateCharge=Math.min(100,m.ultimateCharge+3);}else if(w>=0){const t=tier(p.weaponXP[w]);if(p.weaponPath[w]==='impact')damage*=1+t*.25;if(p.weaponPath[w]==='pierce'&&m.guarded)damage/=(m.guardFactor?.()||.35);if(p.weaponPath[w]==='shatter')m.shattered=Math.min(.24,t*.08);p.weaponXP[w]=Math.min(1e6,p.weaponXP[w]+1);}return damage;}
function kill(m,weapon){const p=m.progress,g=foes.indexOf(m.enemy.art);if(g>=0)p.guide[g]=Math.min(1e6,p.guide[g]+1);award(p,[1,m.boss?3:0,0]);const i=contracts.findIndex(c=>c.id===p.contract);if(!p.finishedContracts?.includes(p.contract)&&(i===0||i===1&&weapon==='melee'&&m.selectedForm==='step-shell'||i===2&&weapon==='melee'&&m.selectedForm==='samurai'||i===3&&m.enemy.art==='gate-hauler'||i===4&&m.boss))p.counts[i]=Math.min(contracts[i].target,p.counts[i]+1);if(p.counts[i]===contracts[i].target)p.notice='Contract ready: '+contracts[i].name+' — tap the crate to collect.';
 const d=m.route,c=captains[d];if(m.boss&&m.stage>=c.stage&&!p.district[d]){p.district[d]=true;award(p,c.reward);if(d===1)m.mods[m.weapon]=Math.min(3,(m.mods[m.weapon]||0)+1);if(d===2)p.weaponXP=p.weaponXP.map(v=>Math.min(1e6,v+100));p.notice=c.name+' defeated! '+c.unlock;}}
function next(p){if(!p.district[0])return 'Defeat Foreman Rusk · Dry Docks, stretch 5 · workshop permit';for(let i=0;i<3;i++)if(!p.build[i])return 'Restore '+buildings[i].name+' · unlock '+buildings[i].unlock.toLowerCase();for(let i=1;i<3;i++)if(!p.district[i])return 'Defeat '+captains[i].name+' · '+['Dry Docks','Drainage Run','Salt Flats'][i]+', stretch '+captains[i].stage;for(let i=0;i<3;i++)if(p.build[i]<3)return 'Improve '+buildings[i].name+' to level '+(p.build[i]+1);return 'Harbor restored · master every weapon and complete the field guide';}
const api={ids,forms,foes,buildings,captains,contracts,expeditions,paths,formPaths,fresh,load,award,buildCost,build,tier,chooseWeapon,chooseForm,selectContract,claimContract,dispatch,collect,hit,kill,next};if(typeof module!=='undefined')module.exports=api;else root.BrineProgression=api;
})(typeof globalThis!=='undefined'?globalThis:this);
