(()=>{
const S=BrineShop,panel=document.querySelector('[data-panel=guns]');let category='shell',selected='deep',shopOpen=false,last='',previewToken=0;
const shop=document.createElement('section');shop.id='scrapyard';shop.hidden=true;
const switcher=document.createElement('nav');switcher.className='scrapyard-switch';switcher.setAttribute('aria-label','Gear sections');switcher.innerHTML='<button data-gear-view="loadout" aria-pressed="true">LOADOUT</button><button data-gear-view="shop" aria-pressed="false">SCRAPYARD SHOP</button>';
panel.prepend(switcher);panel.append(shop);
switcher.onclick=e=>{const b=e.target.closest('[data-gear-view]');if(!b)return;shopOpen=b.dataset.gearView==='shop';panel.classList.toggle('scrapyard-open',shopOpen);shop.hidden=!shopOpen;for(const x of switcher.children)x.setAttribute('aria-pressed',String((x.dataset.gearView==='shop')===shopOpen));last='';render();};
function icon(id){if(['sinker','duck','whoopee','confetti'].includes(id))return '<canvas width="160" height="160" data-projectile-icon="'+id+'" aria-label="'+id+' projectile"></canvas>';const paths={sinker:'<path d="M7 15h50v35H7z" fill="#b96443"/><path d="M7 32h50M24 15v17m17 0v18" stroke="#15363b"/>',whoopee:'<ellipse cx="30" cy="37" rx="23" ry="15" fill="#d8836d"/><path d="M45 25l9-16 7 4-7 19" fill="#d8836d"/>',duck:'<path d="M8 33q12 4 21-3V19a12 12 0 1 1 22 7q5 27-24 29Q9 56 8 33" fill="#e9bf59"/><path d="M52 18h10l-9 8" fill="#cb633c"/><circle cx="44" cy="16" r="2" fill="#092e36"/>',confetti:'<path d="M15 34h33l-4 22H19z" fill="#3f9297"/><path d="M17 23l-6-9m19 6 2-13m14 14 10-10" stroke="#bd5c3b"/><path d="m24 26 7-4 5 7-8 4" fill="#e7bd62"/>'};return '<svg viewBox="0 0 64 64" aria-hidden="true" stroke="#102d35" stroke-width="2">'+paths[id]+'</svg>';}
function equipped(type,id){return type==='shell'?model.shop.shell===id:type==='weapon'?model.shop.weaponPaint===id:model.shop.mods[model.weapon]===id;}
function render(){if(!shopOpen||!ready)return;const key=JSON.stringify([category,selected,model.shop,Math.floor(model.gold),model.best,model.weapon]);if(key===last)return;last=key;const catalog=category==='mod'?S.mods:S.paints;if(!catalog.some(i=>i.id===selected))selected=catalog[0].id;const item=S.item(category,selected),own=S.owned(model,category,selected),locked=model.best<item.unlock;
BrineUI.patch(shop,'<header class="scrap-heading"><div><small>PERMANENT UNLOCKS</small><h2>SCRAPYARD</h2></div><strong>'+BrineTideglass.format(model.gold)+'<small>SALVAGE</small></strong></header><nav class="scrap-tabs" aria-label="Shop categories">'+[['shell','SHELL PAINT'],['weapon','WEAPON PAINT'],['mod','WONKY MODS']].map(([id,n])=>'<button data-category="'+id+'" aria-pressed="'+(category===id)+'">'+n+'</button>').join('')+'</nav><div class="scrap-options">'+catalog.map(i=>'<button data-item="'+i.id+'" aria-pressed="'+(i.id===selected)+'">'+(category==='mod'?icon(i.id):'<i style="background:'+(i.color?'rgb('+i.color.join(',')+')':'#ca6a42')+'"></i>')+'<span>'+i.name+'</span>'+(S.owned(model,category,i.id)?'<small>OWNED</small>':'')+'</button>').join('')+'</div><article class="scrap-detail"><h3>'+item.name+'</h3>'+(category==='mod'?'<div class="scrap-mod-art">'+icon(item.id)+'</div><p>'+item.detail+'</p><p class="scrap-muted">One mod per gun · fitting to '+equippedName()+'. Existing attachment ranks are kept.</p>':'<canvas class="scrap-preview" width="600" height="250" aria-label="Current and selected paint preview"></canvas><p>Permanent '+(category==='shell'?'shell':'weapon casing')+' paint · appearance only.</p><p class="scrap-muted">Orange paint changes. Pale surfaces, dark outlines and transparency stay intact.</p>')+'<button class="scrap-purchase" data-purchase '+(locked||equipped(category,selected)||!own&&model.gold<item.cost?'disabled':'')+'>'+(locked?'CLEAR STRETCH '+item.unlock:equipped(category,selected)?'EQUIPPED':own?'EQUIP': 'UNLOCK · '+BrineTideglass.format(item.cost)+' SALVAGE')+'</button>'+(category==='mod'&&model.shop.mods[model.weapon]?'<button class="scrap-remove" data-remove>REMOVE MOD</button>':'')+'<p class="scrap-result" role="status"></p></article>');
for(const c of shop.querySelectorAll('[data-projectile-icon]')){const id=c.dataset.projectileIcon,im=shopProjectileImages[id],art=BrineProjectileArt[id];if(im?.complete&&art){const f=art.frames[0],k=140/art.size;c.getContext('2d').drawImage(im,f.x,f.y,f.w,f.h,(160-f.w*k)/2,(160-f.h*k)/2,f.w*k,f.h*k);}}
if(category!=='mod')paintPreview(category,item);
}
function equippedName(){return model.settings.weapons.find(w=>w.id===model.weapon)?.name||model.weapon;}
async function paintPreview(type,item){const token=++previewToken,im=new Image();im.src=type==='shell'?'ui/'+(model.selectedForm==='samurai'?'samurai':'step-shell')+'-emblem.png':BrineWeaponArt[model.weapon].image;await im.decode();if(token!==previewToken)return;const out=shop.querySelector('.scrap-preview');if(!out)return;const c=out.getContext('2d');c.clearRect(0,0,out.width,out.height);const temp=document.createElement('canvas');temp.width=im.width;temp.height=im.height;const t=temp.getContext('2d',{willReadFrequently:true});t.drawImage(im,0,0);const raw=t.getImageData(0,0,im.width,im.height),current=S.paints.find(p=>p.id===(type==='shell'?model.shop.shell:model.shop.weaponPaint));const scale=Math.min(260/im.width,205/im.height),w=im.width*scale,h=im.height*scale;
for(const [x,color] of [[20,current.color],[320,item.color]]){const data=new ImageData(new Uint8ClampedArray(raw.data),raw.width,raw.height);S.recolor(data.data,color);t.putImageData(data,0,0);c.drawImage(temp,x+(260-w)/2,10+(205-h)/2,w,h);}c.fillStyle='#0c333b';c.font='bold 19px sans-serif';c.textAlign='center';c.fillText('CURRENT',150,242);c.fillText('PREVIEW',450,242);}
shop.onclick=e=>{const tab=e.target.closest('[data-category]'),choice=e.target.closest('[data-item]');if(tab){category=tab.dataset.category;selected=category==='mod'?'sinker':'deep';last='';render();}else if(choice){selected=choice.dataset.item;last='';render();}else if(e.target.closest('[data-purchase]')&&!e.target.closest('button').disabled){const own=S.owned(model,category,selected);if(own||model.shopBuy(category,selected)){model.shopEquip(category,selected);persist();last='';render();refresh();shop.querySelector('.scrap-result').textContent=own?'Equipped.':'Unlocked and equipped.';}}else if(e.target.closest('[data-remove]')){model.shopEquip('mod','none');persist();last='';render();}};
const old=refresh;refresh=function(){old();render();};
})();
