const Forge=BrineTideglass;
let forgeKey='',campaignTiers=[1,1,1],campaignRepeat=null;
for(const [id,label]of [['campaigns','Campaigns'],['overclock','Overclock']]){const b=document.createElement('button');b.dataset.progressTab=id;b.textContent=label;$('progress-tabs').insertBefore(b,$('progress-tabs').children[id==='campaigns'?1:2]);}
const campaignBanner=document.createElement('button');campaignBanner.id='campaign-banner';campaignBanner.hidden=true;$('screen').append(campaignBanner);campaignBanner.onclick=()=>{if(campaignRepeat&&!model.forge.run){const r=campaignRepeat;campaignRepeat=null;showCampaignEntry(r.id,r.tier);refresh();return;}if(model.forge.run?.complete){const id=model.forge.run.id,tier=model.forge.run.tier;if(model.claimCampaign()){campaignRepeat={id,tier,until:performance.now()+6000};campaignTiers[id]=Math.min(10,model.forge.cleared[id]+1);persist();forgeKey='';refresh();}return;}progressTab='campaigns';openHarbor('camp');};
const progressionBeforeForge=refreshProgressionUI;
refreshProgressionUI=function(){progressionBeforeForge();if(!['campaigns','overclock'].includes(progressTab)||$('drawer').hidden||harborTab!=='camp')return;
 const f=model.forge,key=JSON.stringify([f,progressTab,model.gold,model.best,campaignTiers,model.ultimateActive,model.state==='defeat']);
 // The original renderer may replace this region after its own progress key changes.
 if(key===forgeKey&&progressContent().querySelector('[data-forge-panel]'))return;forgeKey=key;
 let html='<section data-forge-panel><div class="tideglass-bank"><span aria-hidden="true">◆</span><div><strong>'+f.tideglass.toLocaleString()+' TIDEGLASS</strong><small>Earned in campaigns · permanent Overclock upgrades</small></div></div>'+ (f.notice?'<p role="status">'+escapeHarbor(f.notice)+'</p>':'');
 if(progressTab==='overclock'){html+='<p>Permanent bonuses · stack with your build · No rank limit.</p>';html+=Object.entries(Forge.clocks).map(([id,c])=>{const rank=f.overclock[id],max=rank>=c.cap,locked=model.best<10;return card(c.name,`<p>${c.detail}: <b>+${rank*c.step}%${max?'':' → +'+(rank+1)*c.step+'%'}</b></p><p>Rank ${rank} · no limit</p><button data-forge="clock" data-id="${id}" ${max||locked||(f.run&&!f.run.complete)||f.tideglass<Forge.cost(rank)?'disabled':''}>${locked?'Clear stretch 10':max?'Fully overclocked':f.run&&!f.run.complete?'Finish or leave campaign':Forge.cost(rank)+' Tideglass · upgrade'}</button>`);}).join('');}
 if(progressTab==='campaigns'){html+='<p>YOUR MISSION: Win all 5 battles, then collect your cargo beneath the enemy banner to complete the tier. WHY SAIL: Earn Tideglass for permanent Overclock upgrades in Build. Collecting a first clear unlocks the next tier; replay cleared tiers for more currency. Campaigns do not advance your road stage. Ten tiers per campaign. Start with a fresh shell; your road health and charge return afterward. No entry fee, no energy timer. Rewards wait for you to collect.</p>';
 if(f.run){const r=f.run,c=Forge.campaigns[r.id],prize=model.campaignReward(r.id,r.tier);html+=card((r.challenge===undefined?c.name:BrineDepth.challenges[r.challenge].name)+' · tier '+(r.challengeTier||r.tier),`<p>${r.complete?'! CARGO READY':model.state==='defeat'?'Shell cracked — refit to retry this run':'Battle '+(r.wave+1)+' / 5'}</p><p>Reward: ${prize.glass} Tideglass + ${prize.salvage.toLocaleString()} salvage${prize.first?' · first clear':''}</p><button data-forge="${r.complete?'claim':model.state==='defeat'?'retry':'return'}">${r.complete?'COLLECT CARGO':model.state==='defeat'?'REFIT CAMPAIGN':'RETURN TO BATTLE'}</button>${r.complete?'':'<button data-forge="leave">Leave campaign</button>'}`);}
 html+=Forge.campaigns.map((c,i)=>{const max=Math.min(10,f.cleared[i]+1);campaignTiers[i]=Math.min(max,campaignTiers[i]);const tier=campaignTiers[i],reward=(model.normalCampaignReward||model.campaignReward).call(model,i,tier),locked=model.best<c.unlock;return card(c.name,`<p><b>OBJECTIVE</b><br>Clear all 5 battles of ${c.name} and bring the cargo home.</p><p><b>EXPECT AT SEA</b><br>${c.description}</p><p>${f.cleared[i]} / 10 tiers cleared · starts at enemy strength ${c.stage+(tier-1)*15}</p><label for="campaign-tier-${i}">TIER</label> <select id="campaign-tier-${i}" data-campaign-tier="${i}">${Array.from({length:max},(_,t)=>`<option value="${t+1}" ${tier===t+1?'selected':''}>${t+1}${t+1<=f.cleared[i]?' · replay':' · new'}</option>`).join('')}</select><p>${reward.first?'First clear':'Repeat reward'}: <b>${reward.glass} Tideglass</b> + ${reward.salvage.toLocaleString()} salvage</p><button data-forge="enter" data-id="${i}" ${locked||f.run?'disabled':''}>${locked?'Clear stretch '+c.unlock:f.run?(f.run.complete?'Collect cargo to enter':'Campaign in progress'):'ENTER CAMPAIGN'}</button>`);}).join('');}
 BrineUI.patch(progressContent(),html+'</section>');
};
$('progress-content').addEventListener('change',e=>{if(e.target.dataset.campaignTier!==undefined){campaignTiers[+e.target.dataset.campaignTier]=+e.target.value;forgeKey='';refreshProgressionUI();}});
$('progress-content').addEventListener('click',e=>{const b=e.target.closest('[data-forge]');if(!b||b.disabled)return;const a=b.dataset.forge,id=b.dataset.id;let ok=false;if(a==='clock')ok=model.buyOverclock(id);if(a==='enter'){showCampaignEntry(+id,campaignTiers[+id]);return;}if(a==='leave')ok=model.leaveCampaign();if(a==='claim'){const cid=model.forge.run?.id;ok=model.claimCampaign();if(ok)campaignTiers[cid]=Math.min(10,model.forge.cleared[cid]+1);}if(a==='retry')ok=model.retry();if(a==='return')ok=true;if(ok){persist();forgeKey='';if(['enter','retry','return','leave'].includes(a))openHarbor('road');refresh();}});
const forgeRefresh=refresh;refresh=function(){forgeRefresh();if(campaignRepeat&&performance.now()>=campaignRepeat.until)campaignRepeat=null;const r=model.forge.run;campaignBanner.hidden=!r&&!campaignRepeat;campaignBanner.dataset.ready=String(!!r?.complete||!!campaignRepeat);campaignBanner.setAttribute('aria-label',r?.complete?'Collect campaign cargo':'View campaign progress');if(r){if(!r.complete){for(const b of stageTravel.children){b.disabled=true;b.title='Return to the road to farm';b.setAttribute('aria-label',b.title);}}if(r.complete){if(!campaignBanner.querySelector('.cargo-title')||campaignBanner.querySelector('.cargo-title').textContent!=='COLLECT')campaignBanner.innerHTML='<span class="cargo-title">COLLECT</span><span class="cargo-subtitle">CAMPAIGN CARGO</span>';}else campaignBanner.textContent=Forge.campaigns[r.id].name.toUpperCase()+' · '+Math.min(5,r.wave+1)+'/5';if(!r.complete){$('farm').disabled=true;for(let i=0;i<3;i++)$('route-'+i).disabled=true;}if(r.complete){badge($('nav-camp'),'!');badge($('next-goal'),'!');$('goal-eyebrow').textContent='CAMPAIGN COMPLETE';$('goal-detail').textContent='Collect your Tideglass · tap here';$('pause').disabled=false;}}else {$('pause').disabled=false;if(campaignRepeat){if(campaignBanner.querySelector('.cargo-title')?.textContent!=='↻ REPEAT')campaignBanner.innerHTML='<span class="cargo-title">↻ REPEAT</span><span class="cargo-subtitle">CAMPAIGN CARGO</span>';campaignBanner.setAttribute('aria-label','Repeat completed campaign');}}
 for(const b of $('progress-tabs').children)if(b.dataset.progressTab==='campaigns')badge(b,r?.complete?'!':'');
 $('mod-info').textContent='Rank '+model.modRank+'/3 · attachment power scales with this gun’s firing interval. Fitted to this gun; visible on its barrel.';
 };
const forgeGoal=$('next-goal').onclick;$('next-goal').onclick=()=>{if(model.forge.run?.complete){progressTab='campaigns';openHarbor('camp');}else forgeGoal();};

// Keep road simulation running; create the campaign only after arrival.
let campaignEntryTimer;
function showCampaignEntry(id,tier,challenge=null){
 if(campaignEntryTimer||model.forge.run)return;campaignRepeat=null;
 let panel=document.getElementById('campaign-entry');
 if(!panel){panel=document.createElement('div');panel.id='campaign-entry';panel.setAttribute('role','status');panel.innerHTML='<small>SETTING SAIL</small><strong></strong><span>Entering battle…</span><i aria-hidden="true"></i>';$('screen').append(panel);}
 panel.querySelector('strong').textContent=challenge===null?Forge.campaigns[id].name:BrineDepth.challenges[challenge].name;
 panel.hidden=false;openHarbor('road');
 campaignEntryTimer=setTimeout(()=>{
  campaignEntryTimer=null;panel.hidden=true;
  if(challenge===null?model.enterCampaign(id,tier):model.enterChallenge(challenge,tier)){persist();forgeKey='';openHarbor('road');refresh();}
 },1500);
}

const campaignDismiss=document.createElement('button');campaignDismiss.id='campaign-repeat-dismiss';campaignDismiss.textContent='×';campaignDismiss.setAttribute('aria-label','Dismiss repeat campaign');campaignDismiss.hidden=true;$('screen').append(campaignDismiss);
campaignDismiss.onclick=()=>{campaignRepeat=null;refresh();};
const refreshCampaignDismiss=refresh;refresh=function(){refreshCampaignDismiss();campaignDismiss.hidden=!campaignRepeat;};
