(function(root){
'use strict';
const guns=[
 {id:'riveter',name:'Rivet Rattle',unlock:20,damage:9,interval:.65,speed:1150,recoil:.55,description:'Every fifth hit releases a double-strength rivet burst.',effect:'rivets'},
 {id:'harpoon',name:'Keelspike',unlock:35,damage:27,interval:1.6,speed:1000,recoil:1.8,description:'Ignores guard. Deals 35% extra gun damage to captains.',effect:'harpoon'},
 {id:'boiler',name:'Boilerjaw',unlock:50,damage:29,interval:1.9,speed:630,recoil:2.1,description:'Every third hit detonates pressure for triple damage.',effect:'pressure'}
].map(w=>({...w,image:'weapons/'+w.id+'.svg',art:w.id,length:58,gripX:390,gripY:650,muzzleX:1410,muzzleY:420,splitX:620,splitY:535,scale:.05,width:1536,height:1024}));
const upgrades={focus:{name:'Deadeye',unlock:12,cap:100,cost:90,description:'+2% crit chance per rank, up to 200%. Above 100%, roll a second crit tier.'},rupture:{name:'Rupture',unlock:20,cap:30,cost:110,description:'+5% crit damage per rank, up to 300% per crit tier.'},plating:{name:'Bulkhead',unlock:25,cap:20,cost:100,description:'Armor keeps growing. Damage reduction has diminishing returns.'}};
const clocks={power:{name:'Hot Load',detail:'All damage',step:10,cap:Infinity},hull:{name:'Deep Shell',detail:'Maximum health',step:10,cap:Infinity},tempo:{name:'Quick Steam',detail:'Gun firing rate',step:3,cap:Infinity}};
const campaigns=[{id:'breakwater',name:'Breakwater Sweep',unlock:10,stage:6,route:0,description:'Five dock battles. Balanced crews and a captain.',reward:40}, {id:'sluice',name:'Sluice Siege',unlock:25,stage:21,route:1,description:'Drainage crews hit harder. Bring guard penetration and recovery.',reward:55}, {id:'foundry',name:'Old Salt Foundry',unlock:50,stage:46,route:2,description:'Five Salt Flats battles. Heavy resistance and a captain.',reward:75}];
const integer=(v,max)=>Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;
const fresh=()=>({version:1,tideglass:0,overclock:{power:0,hull:0,tempo:0},cleared:[0,0,0],run:null,refundDone:true,notice:''});
function settings(s){return {...s,weapons:[...s.weapons.filter(w=>!guns.some(g=>g.id===w.id)),...guns]};}
function format(value){return Math.abs(value)>=1e15?value.toExponential(2):Math.abs(value)<10000?Number(value.toFixed(2)).toLocaleString('en-US'):value.toLocaleString('en-US',{notation:'compact',maximumFractionDigits:2});}
function cost(rank){return 30+rank*20;}
function install(C,P,J){if(C.prototype.tideglassInstalled)return;C.prototype.tideglassInstalled=true;
 const oldFresh=P.fresh,oldLoad=P.load;P.fresh=function(){const p=oldFresh();p.weaponXP.push(0,0,0);p.weaponPath.push('','','');return p;};P.load=function(raw){const p=oldLoad(raw);p.weaponXP=p.weaponXP.slice(0,3).concat(guns.map((_,i)=>integer(raw?.weaponXP?.[i+3],1e6)));p.weaponPath=p.weaponPath.slice(0,3).concat(guns.map((g,i)=>P.paths[g.id].some(v=>v[0]===raw?.weaponPath?.[i+3])?raw.weaponPath[i+3]:''));return p;};
 for(const g of guns){P.ids.push(g.id);P.paths[g.id]=[['impact','Pressure load','+25% gun damage per mastery tier.'],['tempo','Clockwork feed','15% faster firing per mastery tier.']];if(J)J.rules[g.id]=[g.name,'Clear stretch '+g.unlock,m=>m.best>=g.unlock];}
 for(const [id,u]of Object.entries(upgrades))if(J)J.rules[id]=[u.name,'Clear stretch '+u.unlock,m=>m.best>=u.unlock];
 if(J){J.rules.campaigns=['Campaigns','Clear stretch 10',m=>m.best>=10];J.rules.overclock=['Overclock','Clear stretch 10',m=>m.best>=10];for(const [id,title,text,target,complete]of [
 ['campaigns','Chart a campaign','Open Camp > Campaigns. Win five battles, then collect Tideglass. Your road progress is kept safe.','#nav-camp',m=>m.forge?.cleared.some(Boolean)],
 ['overclock','Fire up the Overclock','Spend earned Tideglass in Camp > Overclock. Each purchase permanently raises the displayed bonus.','#nav-camp',m=>Object.values(m.forge?.overclock||{}).some(Boolean)],
 ...Object.entries(upgrades).map(([id,u])=>[id,u.name,u.description+' Swipe the Road upgrades to find it.','#upgrade-'+id,m=>m.upgrades[id]>0]),
 ...guns.map(g=>[g.id,g.name,'Open Gear and try '+g.name+'. '+g.description,'#nav-guns',m=>m.journey.actions.includes(g.id)])])J.lessons.push({id,title,text,target,complete});}
 const reset=C.prototype.reset;C.prototype.reset=function(){this.settings=settings(this.settings);this.forge=fresh();reset.call(this);for(const id of Object.keys(upgrades))this.upgrades[id]=0;for(const g of guns)this.mods[g.id]=0;this.critMeter=0;this.gunContacts={};};
 const cap=C.prototype.cap;C.prototype.cap=function(k){return k==='focus'?100:k==='rupture'?30:Object.hasOwn(this.upgrades,k)?Infinity:0;};
 const oldCost=C.prototype.cost;C.prototype.cost=function(k){const base=upgrades[k]?.cost||({damage:18,shell:16,speed:30,scavenging:60,patch:45,tide:75})[k];return base?Math.floor(base*1.3**Math.min(30,this.upgrades[k])*Math.max(1,this.upgrades[k]/30)**1.5):Infinity;};
 C.prototype.modCost=function(){return [90,450,1800][this.modRank]||0;};
 Object.defineProperty(C.prototype,'damage',{get(){const w=this.settings.weapons.find(w=>w.id===this.weapon);const bonus=this.upgrades.damage*4+(this.level-1)*2+this.modRank*5;const scale=w.interval,raw=this.rawInterval;return Math.round(Math.max(1,.08/raw)*((w.damage+bonus*scale)*(1+Math.floor(this.upgrades.damage/10)*.1)*(1+Math.max(0,this.progress.build[0]-1)*.05)*(1+(this.forge?.overclock.power||0)*.1)));}});
 const hp=Object.getOwnPropertyDescriptor(C.prototype,'maxPlayerHp').get;
 Object.defineProperty(C.prototype,'maxPlayerHp',{get(){return Math.round(hp.call(this)*(1+Math.floor(this.upgrades.shell/10)*.1)*(1+(this.forge?.overclock.hull||0)*.1));}});
 const interval=Object.getOwnPropertyDescriptor(C.prototype,'interval').get;
 Object.defineProperty(C.prototype,'rawInterval',{get(){const r=this.upgrades.speed,e=r<=30?r:30+30*Math.log1p((r-30)/30);return interval.call(this)*(1+r*.08)/(1+e*.08)/(1+(this.forge?.overclock.tempo||0)*.03);}});
 Object.defineProperty(C.prototype,'interval',{get(){return Math.max(.08,this.rawInterval);}});
 Object.defineProperty(C.prototype,'recoveryPercent',{get(){const r=this.upgrades.patch;return r<=10?12+r*2:32+68*(r-10)/(r+24);}});
 Object.defineProperty(C.prototype,'chargePerHit',{get(){const r=this.upgrades.tide;return r<=8?12+r*2:28+72*(r-8)/(r+28);}});
 C.prototype.upgradeValue=function(k){return k==='damage'?this.damage:k==='shell'?this.maxPlayerHp:k==='speed'?1/this.rawInterval:k==='scavenging'?this.upgrades[k]*5:k==='patch'?this.recoveryPercent:k==='tide'?this.chargePerHit:k==='focus'?this.upgrades[k]*2:k==='rupture'?150+this.upgrades[k]*5:100*this.upgrades[k]/(80+this.upgrades[k]);};
 C.prototype.upgradePreview=function(k){const a=this.upgradeValue(k);this.upgrades[k]++;const b=this.upgradeValue(k);this.upgrades[k]--;const fmt=v=>['speed','patch','tide','plating'].includes(k)?v.toFixed(2):format(v);return fmt(a)+' → '+fmt(b)+(k==='speed'?(this.rawInterval<.08?' power/s':'/s'):['scavenging','patch','focus','rupture','plating'].includes(k)?'%':'');};
 const buy=C.prototype.buy;C.prototype.buy=function(k){const old=this.maxPlayerHp,ok=buy.call(this,k);if(ok&&k==='shell'&&this.state!=='defeat')this.playerHp=Math.min(this.maxPlayerHp,this.playerHp+Math.max(0,this.maxPlayerHp-old-25));return ok;};
 C.prototype.buyOverclock=function(k){const f=this.forge,r=f.overclock[k];if(!Object.hasOwn(clocks,k)||this.best<10||r>=clocks[k].cap||f.tideglass<cost(r)||(f.run&&!f.run.complete))return false;const old=this.maxPlayerHp;f.tideglass-=cost(r);f.overclock[k]++;if(k==='hull'&&this.state!=='defeat')this.playerHp+=this.maxPlayerHp-old;f.notice=clocks[k].name+' upgraded: +'+f.overclock[k]*clocks[k].step+'%';return true;};
 const start=C.prototype.startEncounter;C.prototype.startEncounter=function(){const r=this.forge?.run;if(r&&!r.complete){const c=campaigns[r.id];this.stage=c.stage+(r.tier-1)*15+Math.min(4,r.wave);this.route=c.route;this.farming=false;}start.call(this);this.gunContacts={};};
 const hit=C.prototype.hitEnemy;C.prototype.hitEnemy=function(value,weapon,y,power=1){if(this.state!=='fight'||this.submerged&&weapon!=='melee')return hit.call(this,value,weapon,y,power);const f=this.forge,r=f.run?.complete?null:f.run,best=this.best,gold=this.gold,xp=this.xp,kills=this.kills;const district=[...this.progress.district],materials=[...this.progress.materials];
 if(weapon==='melee')value/=this.settings.weapons.find(w=>w.id===this.weapon).interval;this.critMeter+=Math.min(2,(this.upgrades.focus||0)*.02);const tiers=Math.floor(this.critMeter+1e-9);if(tiers){this.critMeter=Math.max(0,this.critMeter-tiers);value*=1+tiers*(.5+Math.min(30,this.upgrades.rupture||0)*.05);power*=1+.5*tiers;}
 if(weapon!=='melee'){this.gunContacts[weapon]=(this.gunContacts[weapon]||0)+1;const n=this.gunContacts[weapon];if(weapon==='riveter'&&n%5===0){value*=2;power*=1.6;}if(weapon==='boiler'&&n%3===0){value*=3;power*=2;}if(weapon==='harpoon'){if(this.guarded)value/=.35;if(this.boss)value*=1.35;}}
 const previousEffects=new Set(this.effects),targetX=this.enemyX,targetY=572-this.enemy.height*.78;
 if(r)this.progress.district=[true,true,true];hit.call(this,value,weapon,y,power);for(const e of this.effects)if(e.type==='hit'&&!previousEffects.has(e)){e.critTier=tiers;e.targetX=targetX;e.targetY=targetY;e.life=e.duration=tiers?1.15:.85;e.numberLane=[0,-1,1][(this.damageLabelSerial||0)%3];this.damageLabelSerial=(this.damageLabelSerial||0)+1;}for(const e of this.effects)if(e.type==='hit'&&!e.duration)e.duration=.6;if(r)this.progress.district=district;
 if(r&&this.kills>kills){this.best=best;this.gold=gold;this.xp=xp;this.progress.district=district;this.progress.materials=materials;this.lastReward=0;this.effects=this.effects.filter(e=>e.type!=='reward');r.wave++;if(r.wave>=5){r.complete=true;this.restoreRoad();r.roadRestored=true;f.run=r;f.notice='Campaign complete! Road battles continue. Collect cargo in Voyage.';}}
 };
 const tick=C.prototype.tick;C.prototype.tick=function(dt,origin){if(this.paused)return;for(const s of this.enemyShots||[])if(!s.bulkhead){s.damage=Math.max(1,Math.round(s.damage*(80/(80+(this.upgrades.plating||0)))));s.bulkhead=true;}tick.call(this,dt,origin);};
 C.prototype.enterCampaign=function(id,tier){const c=campaigns[id];if(!c||!Number.isInteger(tier)||tier<1||tier>10||tier>this.forge.cleared[id]+1||this.best<c.unlock||this.forge.run||this.ultimateActive||this.state==='defeat')return false;this.forge.run={id,tier,wave:0,complete:false,road:{stage:this.stage,route:this.route,farming:this.farming,hp:this.playerHp,charge:this.charge,ultimateCharge:this.ultimateCharge}};this.playerHp=this.maxPlayerHp;this.charge=0;this.ultimateCharge=0;this.paused=false;this.startEncounter();return true;};
 C.prototype.leaveCampaign=function(){const r=this.forge.run;if(!r||r.complete)return false;this.restoreRoad();this.forge.notice='Campaign left. No Tideglass spent; road restored.';return true;};
 C.prototype.restoreRoad=function(){const r=this.forge.run;if(!r)return;this.forge.run=null;this.stage=r.road.stage;this.route=r.road.route;this.farming=r.road.farming;this.playerHp=Math.min(this.maxPlayerHp,r.road.hp);this.charge=r.road.charge;this.ultimateCharge=r.road.ultimateCharge;if(this.ultimateActive)this.beginRecovery();this.ultimateTime=0;this.meleeAdvance=0;this.paused=false;this.startEncounter();};
 C.prototype.campaignReward=function(id,tier){const first=tier>this.forge.cleared[id];return {glass:first?campaigns[id].reward+tier*10:6+tier*2,salvage:(100+campaigns[id].stage*25)*tier,first};};
 C.prototype.claimCampaign=function(){const r=this.forge.run;if(!r?.complete)return false;const reward=this.campaignReward(r.id,r.tier);this.forge.tideglass=Math.min(Number.MAX_VALUE,this.forge.tideglass+reward.glass);this.gold=Math.min(Number.MAX_VALUE,this.gold+reward.salvage);this.forge.cleared[r.id]=Math.max(this.forge.cleared[r.id],r.tier);this.forge.notice='Cargo collected: '+reward.glass+' Tideglass + '+reward.salvage+' salvage.';if(r.roadRestored)this.forge.run=null;else this.restoreRoad();return true;};
 for(const name of ['chooseRoute','farmLevel','toggleFarm']){const fn=C.prototype[name];C.prototype[name]=function(...a){if(this.forge.run&&!this.forge.run.complete)return false;return fn.apply(this,a);};}
 const equip=C.prototype.equip;C.prototype.equip=function(id){if(this.ultimateActive)return false;return equip.call(this,id);};
 const retry=C.prototype.retry;C.prototype.retry=function(){if(this.forge.run&&!this.forge.run.complete){this.forge.run.wave=0;this.playerHp=this.maxPlayerHp;if(this.ultimateActive)this.beginRecovery();this.ultimateTime=0;this.ultimateCharge=0;this.charge=0;this.meleeAdvance=0;this.paused=false;this.startEncounter();return true;}return retry.call(this);};
 const save=C.prototype.save;C.prototype.save=function(...a){const s=save.apply(this,a);s.forge=JSON.parse(JSON.stringify(this.forge));return s;};
 const load=C.prototype.load;C.prototype.load=function(data,...a){const ok=load.call(this,data,...a);if(!ok)return ok;const raw=data.forge;const f=this.forge=fresh();if(raw?.version===1){f.tideglass=integer(raw.tideglass,Number.MAX_VALUE);for(const k of Object.keys(clocks))f.overclock[k]=integer(raw.overclock?.[k],Number.MAX_SAFE_INTEGER);f.cleared=campaigns.map((_,i)=>integer(raw.cleared?.[i],10));f.notice=typeof raw.notice==='string'?raw.notice.slice(0,180):'';
 const r=raw.run,c=campaigns[r?.id];if(c&&Number.isInteger(r.id)&&Number.isInteger(r.tier)&&r.tier>=1&&r.tier<=Math.min(10,f.cleared[r.id]+1)&&this.best>=c.unlock&&r.road){f.run={id:r.id,tier:r.tier,wave:integer(r.wave,5),complete:r.complete===true&&r.wave===5,roadRestored:r.roadRestored===true,road:{stage:Math.max(1,Math.min(this.best+1,integer(r.road.stage,Number.MAX_SAFE_INTEGER))),route:integer(r.road.route,2),farming:r.road.farming===true,hp:Math.max(1,integer(r.road.hp,Number.MAX_VALUE)),charge:integer(r.road.charge,100),ultimateCharge:integer(r.road.ultimateCharge,100)}};if(!f.run.complete)f.run.wave=Math.min(4,f.run.wave);}}
 if(!raw){let refund=0;for(const k of ['damage','shell','speed','scavenging','patch','tide']){const rank=this.upgrades[k];for(let i=0;i<Math.min(rank,30);i++){this.upgrades[k]=i;refund+=Math.max(0,oldCost.call(this,k)-this.cost(k));}this.upgrades[k]=rank;}this.gold=Math.min(Number.MAX_VALUE,this.gold+refund);if(refund)f.notice='Rebalance credit: '+refund+' salvage returned for earlier upgrade purchases.';}
 this.playerHp=Math.min(this.maxPlayerHp,integer(data.playerHp,Number.MAX_VALUE));this.startEncounter();if(data.defeated||!this.playerHp)this.enter('defeat');if(f.run?.complete&&!f.run.roadRestored){const cargo=f.run;this.restoreRoad();cargo.roadRestored=true;f.run=cargo;}return true;};
}
const api={guns,upgrades,clocks,campaigns,fresh,settings,cost,format,install};if(typeof module!=='undefined')module.exports=api;else{root.BrineTideglass=api;install(root.BrineCombat.Encounter,root.BrineProgression,root.BrineJourney);}
})(typeof globalThis!=='undefined'?globalThis:this);
