(function(root){
'use strict';
const challenges=[{name:'Ironclad Convoy',action:'guard',tip:'Keelspike pierces guard. Brick staggers heavy attacks.',paint:'convoy',color:[178,171,147]},{name:'Repair Syndicate',action:'repair',tip:'Fire Volley during REPAIR INCOMING to interrupt. Strike the opening.',paint:'syndicate',color:[92,174,134]},{name:'Scrap Swarm',action:'burst',tip:'Rivet Rattle and Tideline gain crowd damage. Low Tide scatters the pack.',paint:'swarm',color:[167,100,184]}];
const boats=[{name:'Salvage Skiff',cost:1000000,weight:1},{name:'Tugboat',cost:5000000,weight:2},{name:'Wreck Trawler',cost:20000000,weight:4}];
const fresh=()=>({version:1,cleared:[0,0,0],anchor:null,boats:[0,0,0],crew:[0,0,0],fleetBase:0,fleetAt:Date.now(),fleetEarned:0});
const n=(x,max=1e100)=>Number.isFinite(x)?Math.max(0,Math.min(max,x)):0;
function install(C,S){if(C.prototype.depthInstalled)return;C.prototype.depthInstalled=true;
 const J=root.BrineJourney||(typeof require==='function'?require('./journey.js'):null);if(J){J.rules['challenge-voyages']=['Challenge voyages','Clear stretch 50',m=>m.best>=50];J.rules.fleet=['Salvage fleet','Clear stretch 50',m=>m.best>=50];J.lessons.push({id:'challenge-voyages',title:'Read the enemy',text:'Voyage now has optional challenges. Volley interrupts a repair warning; Step Shell protects against heavy hits. Openings reward damage. Tier 3 earns paint, tiers 5 and 10 earn trophies.',target:'#nav-voyage',complete:m=>m.depth.cleared.some(Boolean)},{id:'fleet',title:'Put your salvage to work',text:'Harbor boats earn salvage automatically, even while away. Upgrade hulls with salvage and train crews with salvage plus Tideglass. No cargo collection is required.',target:'#nav-camp',complete:m=>m.depth.boats.some(Boolean)});}

 for(const c of challenges)if(!S.paints.some(p=>p.id===c.paint))S.paints.push({id:c.paint,name:c.name+' livery',color:c.color,cost:0,unlock:0,challenge:challenges.indexOf(c)});
 const buyPaint=C.prototype.shopBuy;C.prototype.shopBuy=function(type,id){const p=S.paints.find(p=>p.id===id);if(p?.challenge!==undefined&&this.depth.cleared[p.challenge]<3)return false;return buyPaint.call(this,type,id);};
 const reset=C.prototype.reset;C.prototype.reset=function(){this.depth=fresh();reset.call(this);};
 const enemy=Object.getOwnPropertyDescriptor(C.prototype,'enemy').get;Object.defineProperty(C.prototype,'enemy',{get(){const e=enemy.call(this),r=this.forge?.run;return r?.challenge!==undefined&&!r.complete?{...e,action:challenges[r.challenge].action}:e;}});
 const start=C.prototype.startEncounter;C.prototype.startEncounter=function(){start.call(this);this.openingTime=0;this.staggerTime=0;this.heavyCount=0;const r=this.forge?.run;if(r?.challenge!==undefined&&!r.complete){const a=this.depth.anchor,scale=1.32**(r.challengeTier-1);this.hp=this.maxHp=Math.round(a.dps*(this.boss?32:8)*scale*(r.challenge===0?.72:1));}};
 const damage=Object.getOwnPropertyDescriptor(C.prototype,'enemyDamage').get;Object.defineProperty(C.prototype,'enemyDamage',{get(){const r=this.forge?.run;return r?.challenge!==undefined&&!r.complete?Math.round(this.depth.anchor.hp*.025*1.16**(r.challengeTier-1)*(this.boss?1.5:1)):damage.call(this);}});
 const repairFraction=Object.getOwnPropertyDescriptor(C.prototype,'enemyRepairFraction').get;Object.defineProperty(C.prototype,'enemyRepairFraction',{get(){return this.forge?.run?.challenge!==undefined&&!this.forge.run.complete?.02:repairFraction.call(this);}});
 C.prototype.battleIntent=function(){if(this.state!=='fight')return '';if(this.openingTime>0)return 'OPENING · STRIKE NOW';if(this.enemyCycle>=this.enemy.interval-1){if(this.enemy.action==='repair')return 'REPAIR INCOMING · VOLLEY';if(this.boss&&this.heavyCount%3===2)return 'HEAVY ATTACK · SHELL UP';}return '';};
 const volley=C.prototype.volley;C.prototype.volley=function(){const interrupt=this.battleIntent()==='REPAIR INCOMING · VOLLEY';const ok=volley.call(this);if(ok&&interrupt){this.enemyCycle=0;this.openingTime=2.5;}return ok;};
 const tick=C.prototype.tick;C.prototype.tick=function(dt,...args){const live=!this.paused&&this.state!=='defeat',intent=this.battleIntent(),cycle=this.enemyCycle,shots=new Set(this.enemyShots);if(live){this.openingTime=Math.max(0,(this.openingTime||0)-dt);this.staggerTime=Math.max(0,(this.staggerTime||0)-dt);}tick.call(this,dt,...args);if(live&&this.state==='fight'&&this.enemyCycle<cycle){this.heavyCount++;if(intent==='HEAVY ATTACK · SHELL UP'){for(const s of this.enemyShots)if(!shots.has(s))s.damage*=1.8;this.openingTime=2.5;}}};
 const hit=C.prototype.hitEnemy;C.prototype.hitEnemy=function(v,w,y,p=1,secondary=false){const r=this.forge?.run,swarm=r?.challenge===2&&!r.complete;if(!secondary&&this.openingTime>0&&w==='scrap')v*=1.2;if(!secondary&&this.openingTime>0)v*=w==='melee'&&this.selectedForm==='samurai'?1.6:1.35;if(swarm&&!secondary)v*=({riveter:2.1,repeater:1.7,lowtide:1.8})[w]||1;
  if(!secondary&&w!=='melee'&&(this.shopImpactMod===undefined?this.shop?.mods[w]:this.shopImpactMod)==='sinker'&&this.state==='fight'&&!this.submerged&&this.staggerTime<=0){this.enemyCycle=Math.max(0,this.enemyCycle-.6);this.staggerTime=3;}
  return hit.call(this,v,w,y,p,secondary);
 };
 C.prototype.enterChallenge=function(id,tier){if(!Number.isInteger(id)||!challenges[id]||!Number.isInteger(tier)||tier<1||tier>10||tier>this.depth.cleared[id]+1||this.best<50||this.forge.run)return false;this.ensureCalibrated();if(!this.depth.anchor)this.depth.anchor={dps:this.pacing.dps,hp:this.maxPlayerHp};if(!this.enterCampaign(id,1))return false;Object.assign(this.forge.run,{challenge:id,challengeTier:tier});this.charge=100;this.ultimateCharge=100;this.startEncounter();return true;};
 const prize=C.prototype.campaignReward;C.prototype.normalCampaignReward=prize;C.prototype.challengeReward=function(id,tier){const first=tier>this.depth.cleared[id];return {first,glass:first?80+tier*20:10+tier*4,salvage:(10000+tier*5000)*(id+1)};};C.prototype.campaignReward=function(id,tier){const r=this.forge?.run;return r?.challenge!==undefined?this.challengeReward(r.challenge,r.challengeTier):prize.call(this,id,tier);};
 const claim=C.prototype.claimCampaign;C.prototype.claimCampaign=function(){const r=this.forge?.run;if(r?.challenge===undefined)return claim.call(this);if(!r.complete)return false;const reward=this.challengeReward(r.challenge,r.challengeTier);this.gold+=reward.salvage;this.forge.tideglass+=reward.glass;this.depth.cleared[r.challenge]=Math.max(this.depth.cleared[r.challenge],r.challengeTier);if(r.challengeTier>=3)for(const type of ['shell','weapon']){const key=type+':'+challenges[r.challenge].paint;if(!this.shop.owned.includes(key))this.shop.owned.push(key);}if(r.roadRestored)this.forge.run=null;else this.restoreRoad();this.forge.notice='Challenge cargo collected. '+(r.challengeTier>=3?'Livery unlocked in Gear.':'');return true;};
 C.prototype.fleetRate=function(){return this.depth.boats.reduce((sum,rank,i)=>sum+(rank?this.depth.fleetBase*boats[i].weight*(1+(rank-1)*.3)*(1+this.depth.crew[i]*.12):0),0);};
 C.prototype.accrueFleet=function(now=Date.now()){const d=this.depth;if(!d)return 0;const elapsed=Math.max(0,Math.min(8*3600000,now-d.fleetAt)),gain=this.fleetRate()*elapsed/60000;d.fleetAt=Math.max(d.fleetAt,now);this.gold=Math.min(Number.MAX_VALUE,this.gold+gain);d.fleetEarned+=gain;return gain;};
 C.prototype.fleetCost=function(id,crew=false){return Math.round(boats[id].cost*(crew?.4:1)*1.8**(crew?this.depth.crew[id]:this.depth.boats[id]));};
 C.prototype.buyBoat=function(id,crew=false,now=Date.now()){if(!Number.isInteger(id)||!boats[id]||this.best<50||crew&&!this.depth.boats[id])return false;const list=crew?this.depth.crew:this.depth.boats;if(list[id]>=(crew?5:10))return false;const cost=this.fleetCost(id,crew),glass=crew?25*(list[id]+1):0;if(this.gold<cost||this.forge.tideglass<glass)return false;this.accrueFleet(now);if(!this.depth.fleetBase)this.depth.fleetBase=Math.max(1,this.offlineRate*.05);this.gold-=cost;this.forge.tideglass-=glass;list[id]++;return true;};
 const save=C.prototype.save;C.prototype.save=function(now=Date.now()){this.accrueFleet(now);return {...save.call(this,now),depth:JSON.parse(JSON.stringify(this.depth))};};
 const load=C.prototype.load;C.prototype.load=function(data,now=Date.now()){const ok=load.call(this,data,now);if(!ok)return ok;const d=data.depth;this.depth=fresh();if(d?.version===1){this.depth.cleared=[0,1,2].map(i=>Math.floor(n(d.cleared?.[i],10)));this.depth.boats=[0,1,2].map(i=>Math.floor(n(d.boats?.[i],10)));this.depth.crew=[0,1,2].map(i=>Math.floor(n(d.crew?.[i],5)));this.depth.fleetBase=n(d.fleetBase);this.depth.fleetAt=n(d.fleetAt,now)||now;this.depth.fleetEarned=n(d.fleetEarned);if(d.anchor?.dps>0&&d.anchor?.hp>0)this.depth.anchor={dps:n(d.anchor.dps),hp:n(d.anchor.hp)};}
  const r=data.forge?.run;if(this.forge.run&&Number.isInteger(r?.challenge)&&challenges[r.challenge]&&Number.isInteger(r.challengeTier)&&r.challengeTier>=1&&r.challengeTier<=Math.min(10,this.depth.cleared[r.challenge]+1)&&this.depth.anchor){Object.assign(this.forge.run,{challenge:r.challenge,challengeTier:r.challengeTier});if(!this.forge.run.complete){this.startEncounter();if(data.defeated)this.enter('defeat');}}
  this.accrueFleet(now);return ok;
 };
}
const api={challenges,boats,install};if(typeof module!=='undefined')module.exports=api;else{root.BrineDepth=api;install(root.BrineCombat.Encounter,root.BrineShop);}
})(typeof globalThis!=='undefined'?globalThis:this);
